/* ============================================================
   Textes propres à l'outil Coche
   ============================================================ */

/* Le tronc commun est dans commun/textes.js ; seules les clés que cet outil est seul à
   utiliser sont ici, greffées sur la même table, dans les six langues du site. Une clé
   ajoutée plus tard dans une seule langue retombe sur l'anglais : la page reste cohérente
   plutôt que d'afficher des clés brutes. */

Object.entries({
  sousCoche:{
    fr:"Les espèces d'un lieu que tu n'as encore jamais observées, et où et quand aller les chercher.",
    en:"The species of a place you have never recorded yet, and where and when to go and look for them.",
    es:"Las especies de un lugar que todavía no has observado nunca, y dónde y cuándo ir a buscarlas.",
    it:"Le specie di un luogo che non hai ancora mai osservato, e dove e quando andarle a cercare.",
    de:"Die Arten eines Ortes, die du noch nie beobachtet hast – und wo und wann du sie suchen kannst.",
    pt:"As espécies de um lugar que ainda nunca observaste, e onde e quando as procurar."},

  qui:{fr:"Compte iNaturalist", en:"iNaturalist account", es:"Cuenta de iNaturalist", it:"Account iNaturalist", de:"iNaturalist-Konto", pt:"Conta iNaturalist"},
  choisirCompte:{fr:"Indique ton compte iNaturalist, puis un lieu.",
    en:"Enter your iNaturalist account, then a place.",
    es:"Indica tu cuenta de iNaturalist y después un lugar.",
    it:"Indica il tuo account iNaturalist, poi un luogo.",
    de:"Gib dein iNaturalist-Konto an, dann einen Ort.",
    pt:"Indica a tua conta iNaturalist e depois um lugar."},
  phPseudo:{fr:"Ton pseudo iNaturalist…", en:"Your iNaturalist username…", es:"Tu usuario de iNaturalist…", it:"Il tuo nome utente iNaturalist…", de:"Dein iNaturalist-Benutzername…", pt:"O teu nome de utilizador iNaturalist…"},

  attPheno:{fr:"Le calendrier des espèces de la zone est en cours de calcul. Il apparaîtra ici dans quelques instants.",
    en:"The calendar of the area's species is being computed. It will appear here in a moment.",
    es:"Se está calculando el calendario de las especies de la zona. Aparecerá aquí en unos instantes.",
    it:"Il calendario delle specie della zona è in fase di calcolo. Apparirà qui tra pochi istanti.",
    de:"Der Kalender der Arten des Gebiets wird berechnet. Er erscheint gleich hier.",
    pt:"O calendário das espécies da zona está a ser calculado. Aparecerá aqui dentro de instantes."},
  oManquants:{fr:"Liste", en:"List", es:"Lista", it:"Elenco", de:"Liste", pt:"Lista"},
  gSansPoint:{fr:"{0} espèces sur {1} n'ont aucun point dans ce relevé : position floutée par iNaturalist (espèces sensibles), introduites écartées de la collecte, ou plafond d'observations atteint.", en:"{0} species out of {1} have no point in this survey: position obscured by iNaturalist (sensitive species), introduced species left out of the collection, or the observation cap was reached.", es:"{0} especies de {1} no tienen ningún punto en este muestreo: posición difuminada por iNaturalist (especies sensibles), introducidas excluidas de la recogida o tope de observaciones alcanzado.", it:"{0} specie su {1} non hanno alcun punto in questo rilievo: posizione offuscata da iNaturalist (specie sensibili), introdotte escluse dalla raccolta, o tetto di osservazioni raggiunto.", de:"{0} von {1} Arten haben keinen Punkt in dieser Erhebung: von iNaturalist unkenntlich gemachte Position (empfindliche Arten), eingeschleppte Arten nicht erhoben, oder die Beobachtungsgrenze wurde erreicht.", pt:"{0} espécies em {1} não têm qualquer ponto neste levantamento: posição ocultada pelo iNaturalist (espécies sensíveis), introduzidas excluídas da recolha, ou limite de observações atingido."},
  oOu:{fr:"Où ?", en:"Where?", es:"¿Dónde?", it:"Dove?", de:"Wo?", pt:"Onde?"},
  oQuand:{fr:"Quand ?", en:"When?", es:"¿Cuándo?", it:"Quando?", de:"Wann?", pt:"Quando?"},
  videQuand:{
    fr:"Les meilleurs mois pour voir ce qui te manque, et ce qu'il y a à chercher ce mois-ci.",
    en:"The best months to find what you are missing, and what to look for this month.",
    es:"Los mejores meses para ver lo que te falta, y lo que puedes buscar este mes.",
    it:"I mesi migliori per vedere ciò che ti manca, e cosa cercare questo mese.",
    de:"Die besten Monate für das, was dir noch fehlt, und was es diesen Monat zu suchen gibt.",
    pt:"Os melhores meses para ver o que te falta, e o que procurar este mês."},
  qdDetail:{fr:"{0} · {1} espèces", en:"{0} · {1} species", es:"{0} · {1} especies", it:"{0} · {1} specie", de:"{0} · {1} Arten", pt:"{0} · {1} espécies"},
  qdPart:{fr:"{0} % de l'année", en:"{0} % of the year", es:"{0} % del año", it:"{0} % dell'anno", de:"{0} % des Jahres", pt:"{0} % do ano"},
  qdTriObs:{fr:"Nombre d'observations", en:"Number of records", es:"Número de observaciones", it:"Numero di osservazioni", de:"Anzahl Beobachtungen", pt:"Número de observações"},
  qdTriSaison:{fr:"Saisonnalité", en:"Seasonality", es:"Estacionalidad", it:"Stagionalità", de:"Saisonalität", pt:"Sazonalidade"},
  qdTriResp:{fr:"Responsabilité", en:"Responsibility", es:"Responsabilidad", it:"Responsabilità", de:"Verantwortung", pt:"Responsabilidade"},
  qdMaintenant:{fr:"Maintenant ({0} → {1})", en:"Right now ({0} → {1})", es:"Ahora ({0} → {1})", it:"Adesso ({0} → {1})", de:"Jetzt ({0} → {1})", pt:"Agora ({0} → {1})"},
  qdFenetreNom:{fr:"Du {0} au {1}", en:"{0} to {1}", es:"Del {0} al {1}", it:"Dal {0} al {1}", de:"Vom {0} bis {1}", pt:"De {0} a {1}"},
  qdAxe:{fr:"Nombre d'espèces", en:"Number of species", es:"Número de especies", it:"Numero di specie", de:"Artenzahl", pt:"Número de espécies"},
  qdAVoir:{fr:"à voir", en:"to find", es:"por ver", it:"da vedere", de:"zu finden", pt:"por ver"},
  qdDejaVues:{fr:"déjà vues", en:"already seen", es:"ya vistas", it:"già viste", de:"schon gesehen", pt:"já vistas"},
  qdVide:{fr:"Rien ne te manque ce mois-ci.", en:"Nothing missing this month.", es:"Este mes no te falta nada.", it:"Non ti manca nulla questo mese.", de:"Diesen Monat fehlt dir nichts.", pt:"Não te falta nada este mês."},
  oTerrain:{fr:"Carte", en:"Map", es:"Mapa", it:"Mappa", de:"Karte", pt:"Mapa"},
  videTerrain:{
    fr:"La carte de terrain : ta position en direct, les espèces retenues autour de toi, et leurs photos.",
    en:"The field map: your live position, the selected species around you, and their photos.",
    es:"El mapa de campo: tu posición en directo, las especies seleccionadas a tu alrededor y sus fotos.",
    it:"La mappa sul campo: la tua posizione in tempo reale, le specie selezionate intorno a te e le loro foto.",
    de:"Die Geländekarte: deine Live-Position, die ausgewählten Arten um dich herum und ihre Fotos.",
    pt:"O mapa de campo: a tua posição em direto, as espécies retidas à tua volta e as suas fotos."},
  tMeSituer:{fr:"Me situer", en:"Locate me", es:"Ubicarme", it:"Localizzami", de:"Mich orten", pt:"Localizar-me"},
  tSuivi:{fr:"● Suivi en cours", en:"● Tracking", es:"● Seguimiento activo", it:"● Tracciamento attivo", de:"● Verfolgung aktiv", pt:"● Seguimento ativo"},
  tRetenues:{fr:"{0} espèces retenues", en:"{0} species selected", es:"{0} especies seleccionadas", it:"{0} specie selezionate", de:"{0} ausgewählte Arten", pt:"{0} espécies retidas"},
  tAucune:{fr:"aucune espèce retenue", en:"no species selected", es:"ninguna especie seleccionada", it:"nessuna specie selezionata", de:"keine Art ausgewählt", pt:"nenhuma espécie retida"},
  tSansGeoloc:{fr:"Cet appareil ne donne pas la position.",
    en:"This device does not provide a position.",
    es:"Este dispositivo no proporciona la posición.",
    it:"Questo dispositivo non fornisce la posizione.",
    de:"Dieses Gerät liefert keine Position.",
    pt:"Este aparelho não fornece a posição."},
  tGeolocRefus:{fr:"Position refusée : autorise la géolocalisation pour ce site.",
    en:"Position refused: allow geolocation for this site.",
    es:"Posición denegada: permite la geolocalización para este sitio.",
    it:"Posizione negata: autorizza la geolocalizzazione per questo sito.",
    de:"Position verweigert: Erlaube die Standortbestimmung für diese Seite.",
    pt:"Posição recusada: autoriza a geolocalização para este site."},
  oClassement:{fr:"Classement", en:"Ranking", es:"Clasificación", it:"Classifica", de:"Rangliste", pt:"Classificação"},
  videClassement:{
    fr:"Qui a vu le plus d'espèces dans cette zone, et à quelle place tu te situes.",
    en:"Who has seen the most species in this area, and where you stand.",
    es:"Quién ha visto más especies en esta zona, y en qué puesto estás tú.",
    it:"Chi ha visto più specie in questa zona, e a che posto ti trovi.",
    de:"Wer in diesem Gebiet die meisten Arten gesehen hat und auf welchem Platz du stehst.",
    pt:"Quem viu mais espécies nesta zona, e em que lugar estás."},
  clEnCours:{fr:"Lecture en cours…", en:"Reading…", es:"Leyendo…", it:"Lettura in corso…", de:"Wird gelesen…", pt:"A ler…"},
  clTotal:{fr:"{0} contributeurs", en:"{0} contributors", es:"{0} participantes", it:"{0} contributori", de:"{0} Beobachtende", pt:"{0} contribuidores"},
  clToi:{fr:"toi", en:"you", es:"tú", it:"tu", de:"du", pt:"tu"},
  clSansCompte:{
    fr:"Indique ton compte iNaturalist pour voir ta place.",
    en:"Enter your iNaturalist account to see where you stand.",
    es:"Indica tu cuenta de iNaturalist para ver tu puesto.",
    it:"Indica il tuo account iNaturalist per vedere la tua posizione.",
    de:"Gib dein iNaturalist-Konto an, um deinen Platz zu sehen.",
    pt:"Indica a tua conta iNaturalist para ver o teu lugar."},
  clAbsent:{
    fr:"Tu n'apparais pas dans les cent premiers. Ta liste locale en compte {0}.",
    en:"You are not in the first hundred. Your local list holds {0}.",
    es:"No apareces entre los cien primeros. Tu lista local tiene {0}.",
    it:"Non compari tra i primi cento. Il tuo elenco locale ne conta {0}.",
    de:"Du bist nicht unter den ersten hundert. Deine lokale Liste zählt {0}.",
    pt:"Não apareces entre os cem primeiros. A tua lista local tem {0}."},
  oCouverture:{fr:"Complétude", en:"Completeness", es:"Completitud", it:"Completezza", de:"Vollständigkeit", pt:"Completude"},

  sVue:{fr:"vue ici", en:"seen here", es:"vista aquí", it:"vista qui", de:"hier gesehen", pt:"vista aqui"},
  aucuneVue:{fr:"Rien de coché ici", en:"Nothing ticked here", es:"Nada marcado aquí", it:"Niente spuntato qui", de:"Hier nichts abgehakt", pt:"Nada assinalado aqui"},
  aucuneVueD:{fr:"Tout est à faire.", en:"Everything is still to do.", es:"Todo está por hacer.", it:"È tutto da fare.", de:"Alles noch offen.", pt:"Está tudo por fazer."},

  videCarteOu:{
    fr:"Où aller pour voir le plus d'espèces nouvelles, mois par mois.",
    en:"Where to go to see the most new species, month by month.",
    es:"Adónde ir para ver más especies nuevas, mes a mes.",
    it:"Dove andare per vedere più specie nuove, mese per mese.",
    de:"Wohin, um Monat für Monat die meisten neuen Arten zu sehen.",
    pt:"Onde ir para ver o máximo de espécies novas, mês a mês."},
  gEnMemoire:{fr:"● en mémoire · {0}", en:"● from memory · {0}", es:"● en memoria · {0}", it:"● in memoria · {0}", de:"● gespeichert · {0}", pt:"● em memória · {0}"},
  gPeriode:{fr:"Période", en:"Period", es:"Periodo", it:"Periodo", de:"Zeitraum", pt:"Período"},
  gVueJamais:{fr:"Jamais vues", en:"Never seen", es:"Nunca vistas", it:"Mai viste", de:"Nie gesehen", pt:"Nunca vistas"},
  gVueToutes:{fr:"Toutes les espèces", en:"All species", es:"Todas las especies", it:"Tutte le specie", de:"Alle Arten", pt:"Todas as espécies"},
  gEnReserve:{fr:"Déjà collecté", en:"Already collected", es:"Ya recogido", it:"Già raccolto", de:"Bereits erhoben", pt:"Já recolhido"},
  gAucuneReserve:{
    fr:"rien encore — un relevé reste en mémoire une semaine et se reprend d'un clic",
    en:"nothing yet — a survey stays in memory for a week and is one click away",
    es:"nada todavía: un muestreo se guarda una semana en memoria y se recupera con un clic",
    it:"ancora niente — un rilevamento resta in memoria una settimana e si riprende con un clic",
    de:"noch nichts — eine Erhebung bleibt eine Woche gespeichert und ist mit einem Klick wieder da",
    pt:"nada ainda — um levantamento fica em memória uma semana e retoma-se com um clique"},
  gFenetreCourt:{fr:"Maintenant", en:"Right now", es:"Ahora", it:"Adesso", de:"Jetzt", pt:"Agora"},
  gDejaComplet:{
    fr:"La collecte générale contient déjà toutes les observations disponibles : une collecte dédiée ramènerait les mêmes, d'où le bouton éteint.",
    en:"The general collection already holds every available record: a dedicated survey would bring back the same ones, hence the disabled button.",
    es:"La recogida general ya contiene todas las observaciones disponibles: una recogida específica traería las mismas, por eso el botón está desactivado.",
    it:"La raccolta generale contiene già tutte le osservazioni disponibili: una raccolta dedicata riporterebbe le stesse, per questo il pulsante è disattivato.",
    de:"Die allgemeine Erhebung enthält bereits alle verfügbaren Beobachtungen: Eine eigene Erhebung brächte dieselben, daher ist die Schaltfläche deaktiviert.",
    pt:"A recolha geral já contém todas as observações disponíveis: uma recolha dedicada traria as mesmas, daí o botão desativado."},
  gFenetreOpt:{fr:"Maintenant ({0} → {1})", en:"Right now ({0} → {1})", es:"Ahora ({0} → {1})", it:"Adesso ({0} → {1})", de:"Jetzt ({0} → {1})", pt:"Agora ({0} → {1})"},
  gFenetreNom:{fr:"les quatre semaines du {0} au {1}", en:"the four weeks from {0} to {1}", es:"las cuatro semanas del {0} al {1}", it:"le quattro settimane dal {0} al {1}", de:"die vier Wochen vom {0} bis {1}", pt:"as quatro semanas de {0} a {1}"},
  gLancer:{fr:"Collecter", en:"Collect", es:"Recoger", it:"Raccogli", de:"Erheben", pt:"Recolher"},
  gRelancer:{fr:"Recollecter", en:"Collect again", es:"Volver a recoger", it:"Raccogli di nuovo", de:"Neu erheben", pt:"Recolher de novo"},
  gLancerMois:{fr:"Collecter {0} seul", en:"Collect {0} only", es:"Recoger solo {0}", it:"Raccogli solo {0}", de:"Nur {0} erheben", pt:"Recolher só {0}"},
  gRelancerMois:{fr:"Recollecter {0}", en:"Collect {0} again", es:"Volver a recoger {0}", it:"Raccogli di nuovo {0}", de:"{0} neu erheben", pt:"Recolher {0} de novo"},
  gArret:{fr:"Collecte interrompue", en:"Collection interrupted", es:"Recogida interrumpida", it:"Raccolta interrotta", de:"Erhebung abgebrochen", pt:"Recolha interrompida"},
  gArretD:{fr:"Elle reprendra du début si tu la redemandes.",
    en:"It will start again from the beginning if you ask for it.",
    es:"Empezará desde el principio si la vuelves a pedir.",
    it:"Ripartirà dall'inizio se la richiedi di nuovo.",
    de:"Sie beginnt von vorn, wenn du sie erneut startest.",
    pt:"Recomeça do início se a pedires de novo."},
  gEnCours:{fr:"Collecte en cours…", en:"Collecting…", es:"Recogiendo…", it:"Raccolta in corso…", de:"Erhebung läuft…", pt:"A recolher…"},
  gAvant:{
    fr:"Compte une minute. Le relevé est gardé en mémoire.",
    en:"Allow a minute. The survey is kept in memory.",
    es:"Cuenta con un minuto. El muestreo se guarda en memoria.",
    it:"Conta un minuto. Il rilevamento viene tenuto in memoria.",
    de:"Rechne mit einer Minute. Die Erhebung wird gespeichert.",
    pt:"Conta com um minuto. O levantamento fica guardado em memória."},
  duMonde:{fr:"du monde ici", en:"of world total here", es:"del total mundial aquí", it:"del mondo qui", de:"des Weltbestands hier", pt:"do mundo aqui"},
  mesObsIci:{fr:"{0} de toi ici", en:"{0} by you here", es:"{0} tuyas aquí", it:"{0} tue qui", de:"{0} von dir hier", pt:"{0} tuas aqui"},
  mesObsAilleurs:{fr:"{0} de toi ailleurs", en:"{0} by you elsewhere", es:"{0} tuyas en otros lugares", it:"{0} tue altrove", de:"{0} von dir anderswo", pt:"{0} tuas noutros sítios"},
  gAjouter:{fr:"Porter sur la carte", en:"Show on the map", es:"Poner en el mapa", it:"Porta sulla mappa", de:"Auf der Karte zeigen", pt:"Pôr no mapa"},
  gChoisies:{fr:"Sur la carte", en:"On the map", es:"En el mapa", it:"Sulla mappa", de:"Auf der Karte", pt:"No mapa"},
  gSurCarte:{fr:"visibles sur la carte", en:"shown on the map", es:"visibles en el mapa", it:"visibili sulla mappa", de:"auf der Karte sichtbar", pt:"visíveis no mapa"},
  gViderChoix:{fr:"Tout retirer", en:"Clear", es:"Quitar todo", it:"Rimuovi tutto", de:"Alle entfernen", pt:"Retirar tudo"},
  gVoirCarte:{fr:"visibles dans l'onglet Carte, une fois la collecte faite",
    en:"visible in the Map tab, once the collection is done",
    es:"visibles en la pestaña Mapa, una vez hecha la recogida",
    it:"visibili nella scheda Mappa, una volta completata la raccolta",
    de:"im Reiter Karte sichtbar, sobald die Erhebung fertig ist",
    pt:"visíveis no separador Mapa, depois de feita a recolha"},
  gTropChoisies:{fr:"Huit espèces au plus sur la carte : au-delà les couleurs ne se distinguent plus.",
    en:"Eight species at most on the map: beyond that the colours stop being distinguishable.",
    es:"Ocho especies como máximo en el mapa: a partir de ahí los colores ya no se distinguen.",
    it:"Al massimo otto specie sulla mappa: oltre, i colori non si distinguono più.",
    de:"Höchstens acht Arten auf der Karte: Darüber lassen sich die Farben nicht mehr unterscheiden.",
    pt:"No máximo oito espécies no mapa: acima disso as cores deixam de se distinguir."},
  gPodium:{fr:"les trois meilleurs", en:"top three", es:"los tres mejores", it:"i primi tre", de:"die besten drei", pt:"os três melhores"},
  gLegende:{fr:"Espèces manquantes par carreau", en:"Missing species per cell", es:"Especies pendientes por celda", it:"Specie mancanti per cella", de:"Fehlende Arten pro Kachel", pt:"Espécies em falta por quadrícula"},
  gLegendeResp:{fr:"Score de responsabilité par carreau", en:"Responsibility score per cell", es:"Puntuación de responsabilidad por celda", it:"Punteggio di responsabilità per cella", de:"Verantwortungswert pro Kachel", pt:"Pontuação de responsabilidade por quadrícula"},
  mCompte:{fr:"Nombre d'espèces", en:"Species count", es:"Número de especies", it:"Numero di specie", de:"Artenzahl", pt:"Número de espécies"},
  mResp:{fr:"Pondéré par la responsabilité", en:"Weighted by responsibility", es:"Ponderado por la responsabilidad", it:"Ponderato per responsabilità", de:"Nach Verantwortung gewichtet", pt:"Ponderado pela responsabilidade"},
  gDansCarreau:{fr:"dans ce carreau", en:"in this cell", es:"en esta celda", it:"in questa cella", de:"in dieser Kachel", pt:"nesta quadrícula"},
  gCellule:{fr:"{0} espèces qui te manquent ici, sur {1} observations",
    en:"{0} species missing here, from {1} records",
    es:"{0} especies que te faltan aquí, de {1} observaciones",
    it:"{0} specie che ti mancano qui, su {1} osservazioni",
    de:"{0} Arten, die dir hier fehlen, aus {1} Beobachtungen",
    pt:"{0} espécies que te faltam aqui, em {1} observações"},
  gCelluleVide:{fr:"Rien ne te manque dans ce carreau.", en:"Nothing missing in this cell.", es:"No te falta nada en esta celda.", it:"Non ti manca nulla in questa cella.", de:"In dieser Kachel fehlt dir nichts.", pt:"Não te falta nada nesta quadrícula."},

  videManquants:{
    fr:"Indique un compte et un lieu, puis charge : l'inventaire du lieu moins ce que tu as déjà observé.",
    en:"Enter an account and a place, then load: the inventory of the place minus what you have already recorded.",
    es:"Indica una cuenta y un lugar y carga: el inventario del lugar menos lo que ya has observado.",
    it:"Indica un account e un luogo, poi carica: l'inventario del luogo meno ciò che hai già osservato.",
    de:"Gib ein Konto und einen Ort an und lade: das Inventar des Orts abzüglich dessen, was du schon beobachtet hast.",
    pt:"Indica uma conta e um lugar, e carrega: o inventário do lugar menos o que já observaste."},
  videCouverture:{
    fr:"La part de la faune et de la flore locales que tu as déjà observée, branche par branche.",
    en:"The share of the local wildlife you have already recorded, branch by branch.",
    es:"La proporción de la fauna y la flora locales que ya has observado, rama a rama.",
    it:"La quota di fauna e flora locali che hai già osservato, ramo per ramo.",
    de:"Der Anteil der lokalen Tier- und Pflanzenwelt, den du schon beobachtet hast, Ast für Ast.",
    pt:"A parte da fauna e da flora locais que já observaste, ramo a ramo."},

  mListe:{fr:"Liste {0} : {1} espèces sur {2}", en:"List {0}: {1} of {2} species", es:"Lista {0}: {1} especies de {2}", it:"Elenco {0}: {1} specie su {2}", de:"Liste {0}: {1} von {2} Arten", pt:"Lista {0}: {1} espécies de {2}"},
  mSansCompte:{fr:"Aucun compte iNaturalist indiqué.", en:"No iNaturalist account given.", es:"No se ha indicado ninguna cuenta de iNaturalist.", it:"Nessun account iNaturalist indicato.", de:"Kein iNaturalist-Konto angegeben.", pt:"Nenhuma conta iNaturalist indicada."},
  lMonde:{fr:"mondiale", en:"worldwide", es:"mundial", it:"mondiale", de:"weltweit", pt:"mundial"},
  lIci:{fr:"locale", en:"local", es:"local", it:"locale", de:"lokal", pt:"local"},

  sJamais:{fr:"pas vue", en:"not seen", es:"no vista", it:"non vista", de:"nicht gesehen", pt:"não vista"},
  sAilleurs:{fr:"pas ici", en:"not here", es:"no aquí", it:"non qui", de:"nicht hier", pt:"não aqui"},
  dJamais:{fr:"absente de ta liste mondiale — une vraie coche",
    en:"absent from your worldwide list — a genuine tick",
    es:"ausente de tu lista mundial: una especie nueva de verdad",
    it:"assente dal tuo elenco mondiale — una vera novità",
    de:"fehlt auf deiner Weltliste — eine echte neue Art",
    pt:"ausente da tua lista mundial — uma verdadeira estreia"},
  dAilleurs:{fr:"déjà vue ailleurs, mais pas dans cette zone",
    en:"already seen elsewhere, but not in this area",
    es:"ya vista en otro lugar, pero no en esta zona",
    it:"già vista altrove, ma non in questa zona",
    de:"schon anderswo gesehen, aber nicht in diesem Gebiet",
    pt:"já vista noutro sítio, mas não nesta zona"},
  dVue:{fr:"déjà observée ici", en:"already recorded here", es:"ya observada aquí", it:"già osservata qui", de:"hier schon beobachtet", pt:"já observada aqui"},
  vuMonde:{fr:"Déjà vues n'importe où", en:"Already seen anywhere", es:"Ya vistas en cualquier lugar", it:"Già viste ovunque", de:"Schon irgendwo gesehen", pt:"Já vistas em qualquer sítio"},
  vuIci:{fr:"Déjà vues ici", en:"Already seen here", es:"Ya vistas aquí", it:"Già viste qui", de:"Hier schon gesehen", pt:"Já vistas aqui"},

  bCoche:{fr:"de l'inventaire coché", en:"of the inventory ticked", es:"del inventario marcado", it:"dell'inventario spuntato", de:"des Inventars abgehakt", pt:"do inventário assinalado"},
  bCocheMonde:{fr:"vues n'importe où", en:"seen anywhere", es:"vistas en cualquier lugar", it:"viste ovunque", de:"irgendwo gesehen", pt:"vistas em qualquer sítio"},
  bCocheIci:{fr:"vues dans la zone", en:"seen in the area", es:"vistas en la zona", it:"viste nella zona", de:"im Gebiet gesehen", pt:"vistas na zona"},
  bReste:{fr:"restent à voir", en:"still to find", es:"quedan por ver", it:"restano da vedere", de:"noch zu finden", pt:"ainda por ver"},
  qJamais:{fr:"Jamais vues, nulle part", en:"Never seen, anywhere", es:"Nunca vistas, en ningún lugar", it:"Mai viste, da nessuna parte", de:"Nie gesehen, nirgends", pt:"Nunca vistas, em lado nenhum"},
  qPasIci:{fr:"Jamais vues ici", en:"Never seen here", es:"Nunca vistas aquí", it:"Mai viste qui", de:"Hier nie gesehen", pt:"Nunca vistas aqui"},
  qVues:{fr:"Déjà vues, n'importe où", en:"Already seen, anywhere", es:"Ya vistas, en cualquier lugar", it:"Già viste, ovunque", de:"Schon gesehen, irgendwo", pt:"Já vistas, em qualquer sítio"},
  qVuesIci:{fr:"Déjà vues ici", en:"Already seen here", es:"Ya vistas aquí", it:"Già viste qui", de:"Hier schon gesehen", pt:"Já vistas aqui"},
  qTout:{fr:"Tout l'inventaire", en:"The whole inventory", es:"Todo el inventario", it:"Tutto l'inventario", de:"Das ganze Inventar", pt:"Todo o inventário"},


  sansListe:{fr:"Liste personnelle en cours de lecture", en:"Reading your list", es:"Leyendo tu lista personal", it:"Lettura dell'elenco personale in corso", de:"Deine Liste wird gelesen", pt:"A ler a lista pessoal"},
  sansListeD:{fr:"La soustraction attend ta liste. Quelques secondes.",
    en:"The subtraction is waiting for your list. A few seconds.",
    es:"La resta espera a tu lista. Unos segundos.",
    it:"La sottrazione attende il tuo elenco. Qualche secondo.",
    de:"Der Abgleich wartet auf deine Liste. Ein paar Sekunden.",
    pt:"A subtração espera pela tua lista. Uns segundos."},
  toutCoche:{fr:"Rien ne te manque ici", en:"Nothing missing here", es:"Aquí no te falta nada", it:"Non ti manca nulla qui", de:"Hier fehlt dir nichts", pt:"Não te falta nada aqui"},
  toutCocheD:{fr:"Élargis le lieu, ou change de groupe.",
    en:"Widen the place, or change group.",
    es:"Amplía el lugar o cambia de grupo.",
    it:"Allarga il luogo, o cambia gruppo.",
    de:"Erweitere den Ort oder wechsle die Gruppe.",
    pt:"Alarga o lugar ou muda de grupo."},

  mFenetre:{fr:"Observations des quatre semaines autour d'aujourd'hui…",
    en:"Records from the four weeks around today…"},
  rEspece:{fr:"espèce", en:"species", es:"especie", it:"specie", de:"Art", pt:"espécie"},
  gRienAMontrer:{fr:"Rien à cartographier", en:"Nothing to map", es:"Nada que cartografiar", it:"Niente da cartografare", de:"Nichts zu kartieren", pt:"Nada a cartografar"},
  gRienCompte:{fr:"Essaie une autre période, ou élargis la zone.",
    en:"Try another period, or widen the area.",
    es:"Prueba otro periodo o amplía la zona.",
    it:"Prova un altro periodo, o allarga la zona.",
    de:"Versuch einen anderen Zeitraum oder erweitere das Gebiet.",
    pt:"Experimenta outro período ou alarga a zona."},
  gRienResp:{fr:"Les effectifs mondiaux ne sont pas encore connus : repasse au nombre d'espèces.",
    en:"World totals are not known yet: switch back to species count.",
    es:"Aún no se conocen los totales mundiales: vuelve al número de especies.",
    it:"I conteggi mondiali non sono ancora noti: torna al numero di specie.",
    de:"Die weltweiten Zahlen sind noch nicht bekannt: Wechsle zurück zur Artenzahl.",
    pt:"Os efetivos mundiais ainda não são conhecidos: volta ao número de espécies."},
  couvGlobale:{fr:"de l'inventaire coché", en:"of the inventory ticked", es:"del inventario marcado", it:"dell'inventario spuntato", de:"des Inventars abgehakt", pt:"do inventário assinalado"},
  couvEspeces:{fr:"espèces vues ici", en:"species seen here", es:"especies vistas aquí", it:"specie viste qui", de:"hier gesehene Arten", pt:"espécies vistas aqui"},
  couvListe:{fr:"espèces sur ton compte", en:"species on your account", es:"especies en tu cuenta", it:"specie sul tuo account", de:"Arten auf deinem Konto", pt:"espécies na tua conta"},
  aVoir:{fr:"à voir", en:"to find", es:"por ver", it:"da vedere", de:"zu finden", pt:"por ver"}
}).forEach(([k, v]) => { for (const l in v) TEXTES[l][k] = v[l]; });
