/* ============================================================
   Textes et langues
   Partagé par les trois outils.
   ============================================================ */


/* ============================================================
   0. Langues
   ============================================================ */

const TEXTES = {
  fr: {
    sous: "Choisis un lieu et découvre ce qui y vit : quelles espèces, à quelle saison, et ce qu'on y trouve plus qu'ailleurs.",
    lieux: "Lieux",
    groupes: "Groupes d'espèces",
    phLieu: "Costa Rica, Vosges, Cévennes…",
    phTaxon: "Oiseaux, Papillons, Orchidées…",
    charger: "Charger l'inventaire",
    valid: "Observations validées",
    toutesObs: "Toutes les observations",
    nomsCom: "Noms vernaculaires",
    nomsSci: "Noms scientifiques",
    choisirLieu: "Sélectionne un lieu ou un groupe d'espèces.",
    pret: "Prêt à charger.",
    viderMem: "Vider la mémoire",
    oListe: "Liste",
    oCarte: "Carte",
    oResp: "Responsabilité",
    rienCharge: "Aucun inventaire chargé",
    videListe: "Choisis un lieu ci-dessus, puis charge l'inventaire.",
    videResp: "Cet onglet compare les effectifs locaux à ceux d'un territoire plus large.",
    recadrer: "Recadrer sur la zone",
    comparerA: "Utiliser comme référence :",
    phRef: "Le monde entier",
    toutesEsp: "Toutes les espèces",
    menaceesSeul: "Menacées uniquement (VU, EN, CR)",
    aucuneEsp: "Aucune espèce trouvée",
    essaieAutre: "Essaie un lieu plus large ou un autre groupe.",
    phRech: "Chercher une espèce…",
    triObs: "Les plus observées",
    triNom: "Ordre alphabétique",
    taxonomie: "Taxonomie",
    rienIci: "Rien à cet endroit de l'arbre",
    changeBranche: "Change de branche ou de mois.",
    piedPage: "Données, tuiles de densité et photographies : iNaturalist et ses contributeurs. Fond de carte : OpenStreetMap. Chaque photographie reste soumise à la licence choisie par son auteur.",
    especes: "espèces",
    obs: "obs.",
    ceMois: "ce mois",
    tout: "tout",
    tronque: "Ce lieu compte plus de 10 000 espèces, le maximum que l'API renvoie en une fois. Les {0} plus observées sont affichées.",
    limiteFiches: "400 fiches affichées sur {0}. Descends dans l'arbre ou utilise la recherche pour cibler.",
    colEspece: "Espèce",
    colRouge: "Liste rouge",
    colIci: "Ici",
    colPart: "Part",
    monde: "Monde",
    exclusive: "exclusive",
    seuilObs: "seuil {0} obs.",
    pMajeure: "majeure",
    pForte: "forte",
    pNotable: "notable",
    pFaible: "faible",
    sousSeuil: "sous le seuil",
    menacees: "menacées",
    exclusives: "exclusives",
    debordeRef: "Certaines espèces dépassent 100 % : la zone d'étude n'est pas entièrement contenue dans {0}. Choisis un territoire de référence qui l'englobe.",
    noteFloutage: "Les coordonnées des espèces sensibles sont floutées par iNaturalist : leur rattachement au lieu peut être erroné.",
    calculCours: "Calcul en cours",
    effectifsCharg: "Les effectifs de référence se chargent, lot par lot.",
    recomptage: "Recomptage en cours",
    recomptageSur: "Les effectifs sont recalculés sur {0}.",
    mondeEntier: "le monde entier",
    espConnues: "Espèces connues",
    auMoinsUne: "observées au moins une fois",
    observations: "Observations",
    depuis: "depuis {0}",
    completude: "{0} % de complétude",
    nonCalculable: "impossible à calculer",
    grapheMois: "Saisonnalité, toutes années confondues",
    legEspMois: "Espèces différentes vues dans le mois",
    mLecture: "Lecture des espèces ({0}), page {1}…",
    mTaxo: "Chargement de la taxonomie… {0} %",
    mEffectifs: "Effectifs de référence ({0}), lot {1}/{2}…",
    mSaison: "Saisonnalité, {0}…",
    mComplet: "Chargement terminé.",
    mMemoire: "{0} espèces, en mémoire depuis {1}.",
    mAujourdhui: "aujourd'hui",
    mJours: "{0} j",
    mVide: "Mémoire vidée. Le prochain chargement repartira des serveurs.",
    mReseau: "Connexion coupée avec iNaturalist : débit limité, réseau, ou fichier ouvert en local. Attends une minute et relance.",
    mEchec: "Échec du chargement : {0}. Relance quand tu veux.",
    mTaxoPartielle: "Taxonomie incomplète, on continue.",
    mReference: "Référence : {0}.",
    mRecompteEchec: "Le recomptage a échoué. Réessaie.",
    mFiltreMois: "Lecture des espèces vues en {0}…",
    mFiltreApp: "Filtre appliqué : {0}.",
    cAutour: "Autour de ce point",
    cRecherche: "Recherche dans un rayon de {0}…",
    cAucune: "Aucune observation dans {0}.",
    cEspecesDans: "{0} espèces dans {1}",
    cPlusObs: "Les plus observées ici",
    cEchec: "La requête a échoué, réessaie.",
    r_kingdom: "règne",
    r_phylum: "embr.",
    r_class: "classe",
    r_order: "ordre",
    r_suborder: "sous-ordre",
    r_family: "famille",
    r_genus: "genre",
    r_species: "espèce",
    r_subspecies: "sous-espèce",
    i_EX: "Éteinte",
    i_EW: "Éteinte à l'état sauvage",
    i_CR: "En danger critique",
    i_EN: "En danger",
    i_VU: "Vulnérable",
    i_NT: "Quasi menacée",
    i_LC: "Préoccupation mineure",
    i_DD: "Données insuffisantes",
  },
  en: {
    sous: "Pick a place and discover what lives there: which species, in which season, and what is found there more than elsewhere.",
    lieux: "Places",
    groupes: "Species groups",
    phLieu: "Costa Rica, Vosges, Cévennes…",
    phTaxon: "Birds, Butterflies, Orchids…",
    charger: "Load inventory",
    valid: "Verified observations",
    toutesObs: "All observations",
    nomsCom: "Common names",
    nomsSci: "Scientific names",
    choisirLieu: "Select a place or a species group.",
    pret: "Ready to load.",
    viderMem: "Clear cache",
    oListe: "List",
    oCarte: "Map",
    oResp: "Responsibility",
    rienCharge: "No inventory loaded",
    videListe: "Pick a place above, then load the inventory.",
    videResp: "This tab compares local counts with those of a wider territory.",
    recadrer: "Zoom to area",
    comparerA: "Use as reference:",
    phRef: "The whole world",
    toutesEsp: "All species",
    menaceesSeul: "Threatened only (VU, EN, CR)",
    aucuneEsp: "No species found",
    essaieAutre: "Try a larger place or another group.",
    phRech: "Search a species…",
    triObs: "Most observed",
    triNom: "Alphabetical",
    taxonomie: "Taxonomy",
    rienIci: "Nothing at this point of the tree",
    changeBranche: "Switch branch or month.",
    piedPage: "Data, density tiles and photographs: iNaturalist and its contributors. Base map: OpenStreetMap. Each photograph remains under the licence chosen by its author.",
    especes: "species",
    obs: "obs.",
    ceMois: "this month",
    tout: "all",
    tronque: "This place holds more than 10,000 species, the maximum the API returns at once. The {0} most observed are shown.",
    limiteFiches: "400 cards shown out of {0}. Go deeper in the tree or use search to narrow down.",
    colEspece: "Species",
    colRouge: "Red List",
    colIci: "Here",
    colPart: "Share",
    monde: "World",
    exclusive: "exclusive",
    seuilObs: "min {0} obs.",
    pMajeure: "major",
    pForte: "strong",
    pNotable: "notable",
    pFaible: "low",
    sousSeuil: "below threshold",
    menacees: "threatened",
    exclusives: "exclusive",
    debordeRef: "Some species exceed 100%: the study area is not fully contained in {0}. Pick a reference territory that encloses it.",
    noteFloutage: "Coordinates of sensitive species are obscured by iNaturalist: their assignment to the place may be wrong.",
    calculCours: "Calculating",
    effectifsCharg: "Reference counts are loading, batch by batch.",
    recomptage: "Recounting",
    recomptageSur: "Counts are being recomputed over {0}.",
    mondeEntier: "the whole world",
    espConnues: "Known species",
    auMoinsUne: "recorded at least once",
    observations: "Observations",
    depuis: "since {0}",
    completude: "{0}% complete",
    nonCalculable: "cannot be computed",
    grapheMois: "Seasonality, all years combined",
    legEspMois: "Distinct species seen in the month",
    mLecture: "Reading species ({0}), page {1}…",
    mTaxo: "Loading taxonomy… {0}%",
    mEffectifs: "Reference counts ({0}), batch {1}/{2}…",
    mSaison: "Seasonality, {0}…",
    mComplet: "Loading complete.",
    mMemoire: "{0} species, cached since {1}.",
    mAujourdhui: "today",
    mJours: "{0} d",
    mVide: "Cache cleared. The next load will come from the servers.",
    mReseau: "Connection to iNaturalist lost: rate limit, network, or file opened locally. Wait a minute and retry.",
    mEchec: "Load failed: {0}. Retry whenever you like.",
    mTaxoPartielle: "Taxonomy incomplete, carrying on.",
    mReference: "Reference: {0}.",
    mRecompteEchec: "Recount failed. Try again.",
    mFiltreMois: "Reading species seen in {0}…",
    mFiltreApp: "Filter applied: {0}.",
    cAutour: "Around this point",
    cRecherche: "Searching within {0}…",
    cAucune: "No observations within {0}.",
    cEspecesDans: "{0} species within {1}",
    cPlusObs: "Most recorded here",
    cEchec: "The request failed, try again.",
    r_kingdom: "kingdom",
    r_phylum: "phylum",
    r_class: "class",
    r_order: "order",
    r_suborder: "suborder",
    r_family: "family",
    r_genus: "genus",
    r_species: "species",
    r_subspecies: "subspecies",
    i_EX: "Extinct",
    i_EW: "Extinct in the wild",
    i_CR: "Critically endangered",
    i_EN: "Endangered",
    i_VU: "Vulnerable",
    i_NT: "Near threatened",
    i_LC: "Least concern",
    i_DD: "Data deficient",
  },
  es: {
    sous: "Elige un lugar y descubre lo que vive allí: qué especies, en qué estación y qué se encuentra allí más que en otros sitios.",
    lieux: "Lugares",
    groupes: "Grupos de especies",
    phLieu: "Costa Rica, Vosges, Cévennes…",
    phTaxon: "Aves, Mariposas, Orquídeas…",
    charger: "Cargar el inventario",
    valid: "Observaciones validadas",
    toutesObs: "Todas las observaciones",
    nomsCom: "Nombres comunes",
    nomsSci: "Nombres científicos",
    choisirLieu: "Elige un lugar o un grupo de especies.",
    pret: "Listo para cargar.",
    viderMem: "Vaciar la memoria",
    oListe: "Lista",
    oCarte: "Mapa",
    oResp: "Responsabilidad",
    rienCharge: "Ningún inventario cargado",
    videListe: "Elige un lugar arriba y carga el inventario.",
    videResp: "Esta pestaña compara los efectivos locales con los de un territorio más amplio.",
    recadrer: "Encuadrar en la zona",
    comparerA: "Usar como referencia:",
    phRef: "El mundo entero",
    toutesEsp: "Todas las especies",
    menaceesSeul: "Solo amenazadas (VU, EN, CR)",
    aucuneEsp: "No se encontró ninguna especie",
    essaieAutre: "Prueba con un lugar más amplio u otro grupo.",
    phRech: "Buscar una especie…",
    triObs: "Las más observadas",
    triNom: "Orden alfabético",
    taxonomie: "Taxonomía",
    rienIci: "Nada en este punto del árbol",
    changeBranche: "Cambia de rama o de mes.",
    piedPage: "Datos, teselas de densidad y fotografías: iNaturalist y sus colaboradores. Mapa base: OpenStreetMap. Cada fotografía conserva la licencia elegida por su autor.",
    especes: "especies",
    obs: "obs.",
    ceMois: "este mes",
    tout: "todo",
    tronque: "Este lugar tiene más de 10 000 especies, el máximo que devuelve la API de una vez. Se muestran las {0} más observadas.",
    limiteFiches: "400 fichas mostradas de {0}. Baja en el árbol o usa la búsqueda para afinar.",
    colEspece: "Especie",
    colRouge: "Lista Roja",
    colIci: "Aquí",
    colPart: "Proporción",
    monde: "Mundo",
    exclusive: "exclusiva",
    seuilObs: "mín. {0} obs.",
    pMajeure: "mayor",
    pForte: "fuerte",
    pNotable: "notable",
    pFaible: "baja",
    sousSeuil: "bajo el umbral",
    menacees: "amenazadas",
    exclusives: "exclusivas",
    debordeRef: "Algunas especies superan el 100 %: la zona de estudio no está totalmente contenida en {0}. Elige un territorio de referencia que la englobe.",
    noteFloutage: "Las coordenadas de las especies sensibles son difuminadas por iNaturalist: su asignación al lugar puede ser errónea.",
    calculCours: "Calculando",
    effectifsCharg: "Los efectivos de referencia se cargan por lotes.",
    recomptage: "Recuento en curso",
    recomptageSur: "Los efectivos se recalculan sobre {0}.",
    mondeEntier: "el mundo entero",
    espConnues: "Especies conocidas",
    auMoinsUne: "observadas al menos una vez",
    observations: "Observaciones",
    depuis: "desde {0}",
    completude: "{0} % de completitud",
    nonCalculable: "imposible de calcular",
    grapheMois: "Estacionalidad, todos los años juntos",
    legEspMois: "Especies distintas vistas en el mes",
    mLecture: "Leyendo especies ({0}), página {1}…",
    mTaxo: "Cargando la taxonomía… {0} %",
    mEffectifs: "Efectivos de referencia ({0}), lote {1}/{2}…",
    mSaison: "Estacionalidad, {0}…",
    mComplet: "Carga completada.",
    mMemoire: "{0} especies, en memoria desde {1}.",
    mAujourdhui: "hoy",
    mJours: "{0} d",
    mVide: "Memoria vaciada. La próxima carga vendrá de los servidores.",
    mReseau: "Conexión con iNaturalist cortada: límite de peticiones, red o archivo abierto en local. Espera un minuto y reintenta.",
    mEchec: "Fallo de carga: {0}. Reintenta cuando quieras.",
    mTaxoPartielle: "Taxonomía incompleta, continuamos.",
    mReference: "Referencia: {0}.",
    mRecompteEchec: "El recuento ha fallado. Inténtalo de nuevo.",
    mFiltreMois: "Leyendo especies vistas en {0}…",
    mFiltreApp: "Filtro aplicado: {0}.",
    cAutour: "Alrededor de este punto",
    cRecherche: "Buscando en un radio de {0}…",
    cAucune: "Ninguna observación en {0}.",
    cEspecesDans: "{0} especies en {1}",
    cPlusObs: "Las más observadas aquí",
    cEchec: "La consulta ha fallado, reinténtalo.",
    r_kingdom: "reino",
    r_phylum: "filo",
    r_class: "clase",
    r_order: "orden",
    r_suborder: "suborden",
    r_family: "familia",
    r_genus: "género",
    r_species: "especie",
    r_subspecies: "subespecie",
    i_EX: "Extinta",
    i_EW: "Extinta en estado silvestre",
    i_CR: "En peligro crítico",
    i_EN: "En peligro",
    i_VU: "Vulnerable",
    i_NT: "Casi amenazada",
    i_LC: "Preocupación menor",
    i_DD: "Datos insuficientes",
  },
  it: {
    sous: "Scegli un luogo e scopri cosa ci vive: quali specie, in quale stagione e cosa vi si trova più che altrove.",
    lieux: "Luoghi",
    groupes: "Gruppi di specie",
    phLieu: "Costa Rica, Vosges, Cévennes…",
    phTaxon: "Uccelli, Farfalle, Orchidee…",
    charger: "Carica l'inventario",
    valid: "Osservazioni validate",
    toutesObs: "Tutte le osservazioni",
    nomsCom: "Nomi comuni",
    nomsSci: "Nomi scientifici",
    choisirLieu: "Scegli un luogo o un gruppo di specie.",
    pret: "Pronto al caricamento.",
    viderMem: "Svuota la memoria",
    oListe: "Elenco",
    oCarte: "Mappa",
    oResp: "Responsabilità",
    rienCharge: "Nessun inventario caricato",
    videListe: "Scegli un luogo qui sopra, poi carica l'inventario.",
    videResp: "Questa scheda confronta i conteggi locali con quelli di un territorio più ampio.",
    recadrer: "Inquadra la zona",
    comparerA: "Usare come riferimento:",
    phRef: "Il mondo intero",
    toutesEsp: "Tutte le specie",
    menaceesSeul: "Solo minacciate (VU, EN, CR)",
    aucuneEsp: "Nessuna specie trovata",
    essaieAutre: "Prova un luogo più ampio o un altro gruppo.",
    phRech: "Cerca una specie…",
    triObs: "Le più osservate",
    triNom: "Ordine alfabetico",
    taxonomie: "Tassonomia",
    rienIci: "Nulla in questo punto dell'albero",
    changeBranche: "Cambia ramo o mese.",
    piedPage: "Dati, tasselli di densità e fotografie: iNaturalist e i suoi contributori. Mappa di base: OpenStreetMap. Ogni fotografia resta soggetta alla licenza scelta dal suo autore.",
    especes: "specie",
    obs: "oss.",
    ceMois: "questo mese",
    tout: "tutto",
    tronque: "Questo luogo conta più di 10 000 specie, il massimo che l'API restituisce in una volta. Sono mostrate le {0} più osservate.",
    limiteFiches: "400 schede mostrate su {0}. Scendi nell'albero o usa la ricerca per restringere.",
    colEspece: "Specie",
    colRouge: "Lista Rossa",
    colIci: "Qui",
    colPart: "Quota",
    monde: "Mondo",
    exclusive: "esclusiva",
    seuilObs: "soglia {0} oss.",
    pMajeure: "maggiore",
    pForte: "forte",
    pNotable: "notevole",
    pFaible: "bassa",
    sousSeuil: "sotto soglia",
    menacees: "minacciate",
    exclusives: "esclusive",
    debordeRef: "Alcune specie superano il 100%: l'area di studio non è interamente contenuta in {0}. Scegli un territorio di riferimento che la comprenda.",
    noteFloutage: "Le coordinate delle specie sensibili sono offuscate da iNaturalist: la loro attribuzione al luogo può essere errata.",
    calculCours: "Calcolo in corso",
    effectifsCharg: "I conteggi di riferimento si caricano a lotti.",
    recomptage: "Riconteggio in corso",
    recomptageSur: "I conteggi sono ricalcolati su {0}.",
    mondeEntier: "il mondo intero",
    espConnues: "Specie note",
    auMoinsUne: "osservate almeno una volta",
    observations: "Osservazioni",
    depuis: "dal {0}",
    completude: "{0}% di completezza",
    nonCalculable: "impossibile da calcolare",
    grapheMois: "Stagionalità, tutti gli anni insieme",
    legEspMois: "Specie diverse viste nel mese",
    mLecture: "Lettura specie ({0}), pagina {1}…",
    mTaxo: "Caricamento tassonomia… {0}%",
    mEffectifs: "Conteggi di riferimento ({0}), lotto {1}/{2}…",
    mSaison: "Stagionalità, {0}…",
    mComplet: "Caricamento completato.",
    mMemoire: "{0} specie, in memoria da {1}.",
    mAujourdhui: "oggi",
    mJours: "{0} g",
    mVide: "Memoria svuotata. Il prossimo caricamento ripartirà dai server.",
    mReseau: "Connessione con iNaturalist interrotta: limite di richieste, rete o file aperto in locale. Attendi un minuto e riprova.",
    mEchec: "Caricamento fallito: {0}. Riprova quando vuoi.",
    mTaxoPartielle: "Tassonomia incompleta, si continua.",
    mReference: "Riferimento: {0}.",
    mRecompteEchec: "Il riconteggio è fallito. Riprova.",
    mFiltreMois: "Lettura specie viste in {0}…",
    mFiltreApp: "Filtro applicato: {0}.",
    cAutour: "Intorno a questo punto",
    cRecherche: "Ricerca entro {0}…",
    cAucune: "Nessuna osservazione entro {0}.",
    cEspecesDans: "{0} specie entro {1}",
    cPlusObs: "Le più osservate qui",
    cEchec: "La richiesta è fallita, riprova.",
    r_kingdom: "regno",
    r_phylum: "phylum",
    r_class: "classe",
    r_order: "ordine",
    r_suborder: "sottordine",
    r_family: "famiglia",
    r_genus: "genere",
    r_species: "specie",
    r_subspecies: "sottospecie",
    i_EX: "Estinta",
    i_EW: "Estinta in natura",
    i_CR: "In pericolo critico",
    i_EN: "In pericolo",
    i_VU: "Vulnerabile",
    i_NT: "Quasi minacciata",
    i_LC: "Rischio minimo",
    i_DD: "Dati insufficienti",
  },
  de: {
    sous: "Wähle einen Ort und entdecke, was dort lebt: welche Arten, zu welcher Jahreszeit und was dort häufiger ist als anderswo.",
    lieux: "Orte",
    groupes: "Artengruppen",
    phLieu: "Costa Rica, Vosges, Cévennes…",
    phTaxon: "Vögel, Schmetterlinge, Orchideen…",
    charger: "Inventar laden",
    valid: "Bestätigte Beobachtungen",
    toutesObs: "Alle Beobachtungen",
    nomsCom: "Trivialnamen",
    nomsSci: "Wissenschaftliche Namen",
    choisirLieu: "Wähle einen Ort oder eine Artengruppe.",
    pret: "Bereit zum Laden.",
    viderMem: "Speicher leeren",
    oListe: "Liste",
    oCarte: "Karte",
    oResp: "Verantwortung",
    rienCharge: "Kein Inventar geladen",
    videListe: "Wähle oben einen Ort und lade das Inventar.",
    videResp: "Dieser Reiter vergleicht die lokalen Zahlen mit denen eines größeren Gebiets.",
    recadrer: "Auf Gebiet zoomen",
    comparerA: "Als Referenz verwenden:",
    phRef: "Die ganze Welt",
    toutesEsp: "Alle Arten",
    menaceesSeul: "Nur gefährdete (VU, EN, CR)",
    aucuneEsp: "Keine Art gefunden",
    essaieAutre: "Versuche einen größeren Ort oder eine andere Gruppe.",
    phRech: "Art suchen…",
    triObs: "Am häufigsten beobachtet",
    triNom: "Alphabetisch",
    taxonomie: "Taxonomie",
    rienIci: "Nichts an dieser Stelle des Baums",
    changeBranche: "Wechsle Ast oder Monat.",
    piedPage: "Daten, Dichtekacheln und Fotos: iNaturalist und seine Mitwirkenden. Grundkarte: OpenStreetMap. Jedes Foto unterliegt der vom Urheber gewählten Lizenz.",
    especes: "Arten",
    obs: "Beob.",
    ceMois: "diesen Monat",
    tout: "alle",
    tronque: "Dieser Ort umfasst über 10 000 Arten, das Maximum der API pro Abfrage. Gezeigt werden die {0} meistbeobachteten.",
    limiteFiches: "400 von {0} Karten gezeigt. Gehe im Baum tiefer oder nutze die Suche.",
    colEspece: "Art",
    colRouge: "Rote Liste",
    colIci: "Hier",
    colPart: "Anteil",
    monde: "Welt",
    exclusive: "exklusiv",
    seuilObs: "min. {0} Beob.",
    pMajeure: "überragend",
    pForte: "hoch",
    pNotable: "merklich",
    pFaible: "gering",
    sousSeuil: "unter Schwelle",
    menacees: "gefährdet",
    exclusives: "exklusiv",
    debordeRef: "Einige Arten übersteigen 100 %: Das Untersuchungsgebiet liegt nicht vollständig in {0}. Wähle ein umfassenderes Bezugsgebiet.",
    noteFloutage: "Koordinaten sensibler Arten werden von iNaturalist verschleiert: Ihre Zuordnung zum Ort kann falsch sein.",
    calculCours: "Berechnung läuft",
    effectifsCharg: "Die Referenzzahlen laden schubweise.",
    recomptage: "Neuzählung läuft",
    recomptageSur: "Die Zahlen werden über {0} neu berechnet.",
    mondeEntier: "die ganze Welt",
    espConnues: "Bekannte Arten",
    auMoinsUne: "mindestens einmal erfasst",
    observations: "Beobachtungen",
    depuis: "seit {0}",
    completude: "{0} % Vollständigkeit",
    nonCalculable: "nicht berechenbar",
    grapheMois: "Saisonalität, alle Jahre zusammen",
    legEspMois: "Verschiedene Arten im Monat",
    mLecture: "Arten werden gelesen ({0}), Seite {1}…",
    mTaxo: "Taxonomie wird geladen… {0} %",
    mEffectifs: "Referenzzahlen ({0}), Charge {1}/{2}…",
    mSaison: "Saisonalität, {0}…",
    mComplet: "Laden abgeschlossen.",
    mMemoire: "{0} Arten, gespeichert seit {1}.",
    mAujourdhui: "heute",
    mJours: "{0} T",
    mVide: "Speicher geleert. Der nächste Ladevorgang kommt von den Servern.",
    mReseau: "Verbindung zu iNaturalist unterbrochen: Ratenbegrenzung, Netz oder lokal geöffnete Datei. Warte eine Minute und lade erneut.",
    mEchec: "Laden fehlgeschlagen: {0}. Jederzeit erneut versuchen.",
    mTaxoPartielle: "Taxonomie unvollständig, es geht weiter.",
    mReference: "Referenz: {0}.",
    mRecompteEchec: "Neuzählung fehlgeschlagen. Bitte erneut.",
    mFiltreMois: "Arten im {0} werden gelesen…",
    mFiltreApp: "Filter angewendet: {0}.",
    cAutour: "Um diesen Punkt",
    cRecherche: "Suche im Umkreis von {0}…",
    cAucune: "Keine Beobachtungen innerhalb von {0}.",
    cEspecesDans: "{0} Arten innerhalb von {1}",
    cPlusObs: "Hier am häufigsten erfasst",
    cEchec: "Die Anfrage schlug fehl, bitte erneut.",
    r_kingdom: "Reich",
    r_phylum: "Stamm",
    r_class: "Klasse",
    r_order: "Ordnung",
    r_suborder: "Unterordnung",
    r_family: "Familie",
    r_genus: "Gattung",
    r_species: "Art",
    r_subspecies: "Unterart",
    i_EX: "Ausgestorben",
    i_EW: "In der Natur ausgestorben",
    i_CR: "Vom Aussterben bedroht",
    i_EN: "Stark gefährdet",
    i_VU: "Gefährdet",
    i_NT: "Potenziell gefährdet",
    i_LC: "Nicht gefährdet",
    i_DD: "Ungenügende Daten",
  },

  pt: {
    sous: "Escolhe um lugar e descobre o que lá vive: que espécies, em que estação e o que lá se encontra mais do que noutros sítios.",
    lieux: "Lugares",
    groupes: "Grupos de espécies",
    phLieu: "Costa Rica, Serra da Mantiqueira, Alentejo…",
    phTaxon: "Aves, Borboletas, Orquídeas…",
    charger: "Carregar o inventário",
    valid: "Observações validadas",
    toutesObs: "Todas as observações",
    nomsCom: "Nomes populares",
    nomsSci: "Nomes científicos",
    choisirLieu: "Seleciona um lugar ou um grupo de espécies.",
    pret: "Pronto para carregar.",
    viderMem: "Limpar a memória",
    oListe: "Lista",
    oCarte: "Mapa",
    oResp: "Responsabilidade",
    rienCharge: "Nenhum inventário carregado",
    videListe: "Escolhe um lugar acima e carrega o inventário.",
    videResp: "Esta aba compara os efetivos locais aos de um território mais amplo.",
    recadrer: "Enquadrar na zona",
    comparerA: "Usar como referência:",
    phRef: "O mundo inteiro",
    toutesEsp: "Todas as espécies",
    menaceesSeul: "Somente ameaçadas (VU, EN, CR)",
    aucuneEsp: "Nenhuma espécie encontrada",
    essaieAutre: "Tenta um lugar mais amplo ou outro grupo.",
    phRech: "Procurar uma espécie…",
    triObs: "As mais observadas",
    triNom: "Ordem alfabética",
    taxonomie: "Taxonomia",
    rienIci: "Nada neste ponto da árvore",
    changeBranche: "Muda de ramo ou de mês.",
    piedPage: "Dados, camadas de densidade e fotografias: iNaturalist e seus colaboradores. Base cartográfica: OpenStreetMap. Cada fotografia continua sujeita à licença escolhida pelo autor.",
    especes: "espécies",
    obs: "obs.",
    ceMois: "neste mês",
    tout: "tudo",
    tronque: "Este lugar tem mais de 10 000 espécies, o máximo que a API devolve de uma vez. São exibidas as {0} mais observadas.",
    limiteFiches: "400 fichas exibidas de {0}. Desce na árvore ou usa a busca para restringir.",
    colEspece: "Espécie",
    colRouge: "Lista vermelha",
    colIci: "Aqui",
    colPart: "Parcela",
    monde: "Mundo",
    exclusive: "exclusiva",
    seuilObs: "limiar {0} obs.",
    pMajeure: "maior",
    pForte: "forte",
    pNotable: "notável",
    pFaible: "baixa",
    sousSeuil: "abaixo do limiar",
    menacees: "ameaçadas",
    exclusives: "exclusivas",
    debordeRef: "Algumas espécies passam de 100 %: a zona de estudo não está inteiramente contida em {0}. Escolhe um território de referência que a englobe.",
    noteFloutage: "As coordenadas das espécies sensíveis são ocultadas pelo iNaturalist: a sua atribuição ao lugar pode estar errada.",
    calculCours: "Cálculo em curso",
    effectifsCharg: "Os efetivos de referência estão a ser carregados, lote a lote.",
    recomptage: "Recontagem em curso",
    recomptageSur: "Os efetivos são recalculados sobre {0}.",
    mondeEntier: "o mundo inteiro",
    espConnues: "Espécies conhecidas",
    auMoinsUne: "observadas ao menos uma vez",
    observations: "Observações",
    depuis: "desde {0}",
    completude: "{0} % de completude",
    nonCalculable: "impossível calcular",
    grapheMois: "Sazonalidade, todos os anos reunidos",
    legEspMois: "Espécies distintas vistas no mês",
    mLecture: "Leitura das espécies ({0}), página {1}…",
    mTaxo: "Carregando a taxonomia… {0} %",
    mEffectifs: "Efetivos de referência ({0}), lote {1}/{2}…",
    mSaison: "Sazonalidade, {0}…",
    mComplet: "Carregamento concluído.",
    mMemoire: "{0} espécies, em memória desde {1}.",
    mAujourdhui: "hoje",
    mJours: "{0} d",
    mVide: "Memória limpa. O próximo carregamento virá dos servidores.",
    mReseau: "Ligação interrompida com o iNaturalist: limite de tráfego, rede, ou ficheiro aberto localmente. Espera um minuto e tenta de novo.",
    mEchec: "Falha no carregamento: {0}. Tenta quando quiseres.",
    mTaxoPartielle: "Taxonomia incompleta, continuamos.",
    mReference: "Referência: {0}.",
    mRecompteEchec: "A recontagem falhou. Tenta de novo.",
    mFiltreMois: "Leitura das espécies vistas em {0}…",
    mFiltreApp: "Filtro aplicado: {0}.",
    cAutour: "Em torno deste ponto",
    cRecherche: "Busca num raio de {0}…",
    cAucune: "Nenhuma observação em {0}.",
    cEspecesDans: "{0} espécies em {1}",
    cPlusObs: "As mais observadas aqui",
    cEchec: "A consulta falhou, tenta de novo.",
    r_kingdom: "reino",
    r_phylum: "filo",
    r_class: "classe",
    r_order: "ordem",
    r_suborder: "subordem",
    r_family: "família",
    r_genus: "género",
    r_species: "espécie",
    r_subspecies: "subespécie",
    i_EX: "Extinta",
    i_EW: "Extinta na natureza",
    i_CR: "Criticamente em perigo",
    i_EN: "Em perigo",
    i_VU: "Vulnerável",
    i_NT: "Quase ameaçada",
    i_LC: "Pouco preocupante",
    i_DD: "Dados insuficientes"
  }
};


/* Compléments ajoutés après coup, fusionnés dans le dictionnaire principal. */
Object.entries({
  cRayon:{fr:"rayon {0}",en:"{0} radius",es:"radio {0}",it:"raggio {0}",de:"Radius {0}",pt:"raio {0}"},
  oDecouverte:{fr:"Découvertes",en:"Discoveries",es:"Descubrimientos",it:"Scoperte",de:"Entdeckungen",pt:"Novidades"},
  videDecouverte:{fr:"Cet onglet liste les espèces vues pour la première fois dans la zone.",en:"This tab lists the species recorded in the area for the first time.",es:"Esta pestaña lista las especies observadas por primera vez en la zona.",it:"Questa scheda elenca le specie osservate per la prima volta nella zona.",de:"Dieser Reiter listet die erstmals im Gebiet erfassten Arten.",pt:"Esta aba lista as espécies vistas pela primeira vez na zona."},
  decFenetre:{fr:"depuis {0}",en:"over {0}",es:"desde {0}",it:"da {0}",de:"seit {0}",pt:"há {0}"},
  decCharge:{fr:"Recherche des nouveautés…",en:"Looking for newcomers…",es:"Buscando novedades…",it:"Ricerca delle novità…",de:"Suche nach Neuzugängen…",pt:"Procurando novidades…"},
  decVide:{fr:"Aucune espèce nouvelle sur cette période.",en:"No new species over this period.",es:"Ninguna especie nueva en este periodo.",it:"Nessuna specie nuova in questo periodo.",de:"Keine neue Art in diesem Zeitraum.",pt:"Nenhuma espécie nova neste período."},
  decMondiale:{fr:"Première mondiale",en:"World first",es:"Primera mundial",it:"Prima mondiale",de:"Weltweit erstmals",pt:"Primeira mundial"},
  decNb:{fr:"{0} espèces nouvelles",en:"{0} new species",es:"{0} especies nuevas",it:"{0} specie nuove",de:"{0} neue Arten",pt:"{0} espécies novas"},
  decFiltreTout:{fr:"Toutes les nouveautés",en:"All new species",es:"Todas las novedades",pt:"Todas as novidades",it:"Tutte le novità",de:"Alle Neuzugänge"},
  decFiltreMond:{fr:"Premières mondiales",en:"World firsts",es:"Primeras mundiales",pt:"Primeiras mundiais",it:"Prime mondiali",de:"Welterstnachweise"},
  disFiltreTout:{fr:"Toutes les espèces",en:"All species",es:"Todas las especies",pt:"Todas as espécies",it:"Tutte le specie",de:"Alle Arten"},
  disFiltreRouge:{fr:"Menacées seulement",en:"Threatened only",es:"Solo amenazadas",pt:"Apenas ameaçadas",it:"Solo minacciate",de:"Nur gefährdete"},
  decNote:{fr:"Nouvelle ici, pas nouvelle pour la science : aucune observation antérieure n'avait été enregistrée dans la zone.",en:"New here, not new to science: no earlier observation had been recorded in the area.",es:"Nueva aquí, no nueva para la ciencia: no había registros anteriores en la zona.",pt:"Nova aqui, não nova para a ciência: não havia registos anteriores na zona.",it:"Nuova qui, non nuova per la scienza: nessuna segnalazione anteriore nella zona.",de:"Neu hier, nicht neu für die Wissenschaft: kein früherer Nachweis im Gebiet."},
  divergent:{fr:"estimations divergentes",en:"estimates disagree",es:"estimaciones divergentes",it:"stime divergenti",de:"Schätzungen weichen ab",pt:"estimativas divergentes"},
  aideDivergent:{fr:"Les deux estimations s'écartent de plus de 15 %. Lis une fourchette, pas un chiffre : il manque des observations.",en:"The two estimates differ by over 15%. Read a range, not a figure: more observations are needed.",es:"Las dos estimaciones difieren en más del 15 %. Lee un intervalo, no una cifra: faltan observaciones.",it:"Le due stime divergono di oltre il 15%. Leggi un intervallo, non una cifra: mancano osservazioni.",de:"Die Schätzungen weichen um über 15 % ab. Lies eine Spanne, keine Zahl: Es fehlen Beobachtungen.",pt:"As duas estimativas diferem em mais de 15 %. Lê um intervalo, não um número: faltam observações."},
  observateurs:{fr:"Observateurs",en:"Observers",es:"Observadores",it:"Osservatori",de:"Beobachtende",pt:"Observadores"},
  obsParPers:{fr:"{0} observations chacun en moyenne",en:"{0} observations each on average",es:"{0} observaciones cada uno de media",it:"{0} osservazioni ciascuno in media",de:"{0} Beobachtungen im Schnitt",pt:"{0} observações cada, em média"},
  retirerRef:{fr:"Revenir au monde entier",en:"Back to the whole world",es:"Volver al mundo entero",it:"Torna al mondo intero",de:"Zurück zur ganzen Welt",pt:"Voltar ao mundo inteiro"},
  pExclusive:{fr:"quasi exclusive",en:"near-exclusive",es:"casi exclusiva",it:"quasi esclusiva",de:"nahezu ausschließlich",pt:"quase exclusiva"},
  pTresForte:{fr:"très forte",en:"very high",es:"muy alta",it:"molto alta",de:"sehr hoch",pt:"muito alta"},
  respDouteux:{fr:"Effectif de référence incohérent : il est inférieur à l'effectif local, ce qui est impossible. La part n'est pas calculable pour cette espèce.",en:"Inconsistent reference count: lower than the local count, which is impossible. The share cannot be computed for this species.",es:"Efectivo de referencia incoherente: es inferior al local, lo que es imposible. La proporción no puede calcularse para esta especie.",pt:"Efetivo de referência incoerente: inferior ao local, o que é impossível. A parcela não pode ser calculada para esta espécie.",it:"Effettivo di riferimento incoerente: inferiore a quello locale, il che è impossibile. La quota non è calcolabile per questa specie.",de:"Widersprüchliche Referenzzahl: niedriger als die lokale Zahl, was unmöglich ist. Der Anteil ist für diese Art nicht berechenbar."},
  introTitre:{fr:"Introduite dans la zone d'étude",en:"Introduced in the study area",es:"Introducida en la zona de estudio",pt:"Introduzida na zona de estudo",it:"Introdotta nella zona di studio",de:"Im Untersuchungsgebiet eingeführt"},
  filtreIntroTout:{fr:"Indigènes et introduites",en:"Native and introduced",es:"Nativas e introducidas",pt:"Nativas e introduzidas",it:"Native e introdotte",de:"Einheimisch und eingeführt"},
  filtreIntroSans:{fr:"Sans les introduites",en:"Without introduced",es:"Sin las introducidas",pt:"Sem as introduzidas",it:"Senza le introdotte",de:"Ohne eingeführte"},
  filtreIntroSeul:{fr:"Introduites seulement",en:"Introduced only",es:"Solo introducidas",pt:"Apenas introduzidas",it:"Solo introdotte",de:"Nur eingeführte"},
  respIntro:{fr:"Part des observations connues d'une espèce qui provient de cette zone. Attention au biais : une espèce peut y être davantage prospectée sans y être plus présente.",en:"Share of a species' known records that comes from this area. Mind the bias: a species may simply be better surveyed here, not more present.",es:"Proporción de los registros conocidos de una especie que procede de esta zona. Cuidado con el sesgo: una especie puede estar mejor prospectada aquí sin ser más abundante.",pt:"Parcela dos registos conhecidos de uma espécie que provém desta zona. Atenção ao viés: uma espécie pode ser mais prospetada aqui sem ser mais presente.",it:"Quota delle segnalazioni note di una specie proveniente da questa zona. Attenzione al bias: una specie può essere semplicemente più cercata qui, non più presente.",de:"Anteil der bekannten Nachweise einer Art aus diesem Gebiet. Vorsicht vor Verzerrung: Eine Art kann hier schlicht besser erfasst sein, nicht häufiger."},
  espEstimees:{fr:"Espèces estimées",en:"Estimated species",es:"Especies estimadas",pt:"Espécies estimadas",it:"Specie stimate",de:"Geschätzte Arten"},
  aideEstim:{fr:"Nombre total d'espèces présentes, invisibles comprises, encadré par deux estimateurs : Chao1, déduit des espèces vues une ou deux fois, et ACE, plus stable. Un écart marqué signale qu'il manque des observations.",en:"Total number of species present, unseen ones included, bracketed by two estimators: Chao1, derived from species seen once or twice, and ACE, steadier. A wide gap means observations are missing.",es:"Número total de especies presentes, incluidas las no vistas, acotado por dos estimadores: Chao1, deducido de las especies vistas una o dos veces, y ACE, más estable. Una diferencia marcada indica que faltan observaciones.",pt:"Número total de espécies presentes, incluindo as não vistas, delimitado por dois estimadores: Chao1, deduzido das espécies vistas uma ou duas vezes, e ACE, mais estável. Uma diferença marcada indica que faltam observações.",it:"Numero totale di specie presenti, comprese le non viste, delimitato da due stimatori: Chao1, dedotto dalle specie viste una o due volte, e ACE, più stabile. Uno scarto marcato indica che mancano osservazioni.",de:"Gesamtzahl vorhandener Arten, ungesehene eingeschlossen, eingegrenzt von zwei Schätzern: Chao1, aus ein- oder zweimal gesehenen Arten, und ACE, stabiler. Ein großer Abstand zeigt fehlende Beobachtungen."},
  oDisparition:{fr:"Disparitions",en:"Disappearances",es:"Desapariciones",it:"Scomparse",de:"Verschwunden",pt:"Desaparecimentos"},
  videDisparition:{fr:"Cet onglet liste les espèces bien connues de la zone qui n'y ont plus été revues.",en:"This tab lists species once well recorded in the area that have not been seen since.",es:"Esta pestaña lista especies antes bien registradas en la zona que ya no se han vuelto a ver.",it:"Questa scheda elenca le specie un tempo ben documentate nella zona e non più riviste.",de:"Dieser Reiter listet einst gut belegte Arten, die im Gebiet nicht mehr gesehen wurden.",pt:"Esta aba lista espécies antes bem registadas na zona e não mais revistas."},
  uniteAn:{fr:"an",en:"year",es:"año",it:"anno",de:"Jahr",pt:"ano"},
  uniteAns:{fr:"ans",en:"years",es:"años",it:"anni",de:"Jahre",pt:"anos"},
  uniteMois:{fr:"mois",en:"month",es:"mes",it:"mese",de:"Monat",pt:"mês"},
  uniteMoisP:{fr:"mois",en:"months",es:"meses",it:"mesi",de:"Monate",pt:"meses"},
  disCharge:{fr:"Recherche des absences…",en:"Looking for absences…",es:"Buscando ausencias…",it:"Ricerca delle assenze…",de:"Suche nach Ausbleibenden…",pt:"Procurando ausências…"},
  disVide:{fr:"Aucune espèce bien documentée n'a cessé d'être observée.",en:"No well-documented species has stopped being recorded.",es:"Ninguna especie bien documentada ha dejado de observarse.",it:"Nessuna specie ben documentata ha smesso di essere osservata.",de:"Keine gut belegte Art ist ausgeblieben.",pt:"Nenhuma espécie bem documentada deixou de ser observada."},
  disNb:{fr:"{0} espèces non revues",en:"{0} species not seen since",es:"{0} especies no vistas",it:"{0} specie non riviste",de:"{0} nicht mehr gesehene Arten",pt:"{0} espécies não revistas"},
  disDerniere:{fr:"vue pour la dernière fois",en:"last seen",es:"vista por última vez",it:"vista l'ultima volta",de:"zuletzt gesehen",pt:"vista pela última vez"},
  disNote:{fr:"Ces espèces n'ont plus été signalées dans la zone depuis au moins deux ans. Cela ne signifie pas pour autant qu'elles ont disparu : peut-être n'ont-elles simplement pas été recherchées.",en:"These species have not been reported in the area for at least two years. That does not mean they are gone: perhaps no one has looked for them.",es:"Estas especies no se registran en la zona desde hace al menos dos años. Eso no significa que hayan desaparecido: quizá simplemente nadie las haya buscado.",pt:"Estas espécies não são registadas na zona há pelo menos dois anos. Isso não significa que tenham desaparecido: talvez ninguém as tenha procurado.",it:"Queste specie non sono più state segnalate nella zona da almeno due anni. Ciò non significa che siano scomparse: forse nessuno le ha cercate.",de:"Diese Arten wurden im Gebiet seit mindestens zwei Jahren nicht mehr gemeldet. Das heißt nicht, dass sie verschwunden sind: vielleicht hat sie schlicht niemand gesucht."},
  avertFichier:{fr:"Page ouverte depuis un fichier local : le navigateur bloque alors les appels à iNaturalist. Mets le fichier en ligne, ou ouvre-le via un serveur local.",en:"Page opened from a local file: the browser then blocks calls to iNaturalist. Put the file online, or serve it from a local server.",es:"Página abierta desde un archivo local: el navegador bloquea las llamadas a iNaturalist. Publica el archivo en línea o ábrelo mediante un servidor local.",it:"Pagina aperta da un file locale: il browser blocca le chiamate a iNaturalist. Pubblica il file online oppure aprilo tramite un server locale.",de:"Seite aus einer lokalen Datei geöffnet: Der Browser blockiert dann Aufrufe an iNaturalist. Lade die Datei online hoch oder nutze einen lokalen Server.",pt:"Página aberta a partir de um ficheiro local: o navegador bloqueia então as chamadas ao iNaturalist. Publica o ficheiro online ou abre-o através de um servidor local."},
  erreurJs:{fr:"Erreur interne : {0}",en:"Internal error: {0}",es:"Error interno: {0}",it:"Errore interno: {0}",de:"Interner Fehler: {0}",pt:"Erro interno: {0}"},
  zoneVue:{fr:"Utiliser cette vue comme zone",en:"Use this view as the area",es:"Usar esta vista como zona",it:"Usa questa vista come zona",de:"Diesen Ausschnitt als Gebiet",pt:"Usar esta vista como zona"},
  zoneTracee:{fr:"Zone dessinée",en:"Drawn area",es:"Zona dibujada",it:"Zona disegnata",de:"Gezeichnetes Gebiet",pt:"Zona desenhada"},
  mNoms:{fr:"Noms vernaculaires : {0} / {1}",en:"Common names: {0} / {1}",es:"Nombres comunes: {0} / {1}",it:"Nomi comuni: {0} / {1}",de:"Volkstümliche Namen: {0} / {1}",pt:"Nomes populares: {0} / {1}"},
  horsLigne:{fr:"Hors ligne : seuls les inventaires déjà en mémoire sont consultables.",en:"Offline: only inventories already in memory can be opened.",es:"Sin conexión: solo se pueden abrir los inventarios ya en memoria.",pt:"Sem ligação: apenas os inventários já em memória podem ser abertos.",it:"Non in linea: solo gli inventari già in memoria sono consultabili.",de:"Offline: Nur bereits gespeicherte Inventare sind abrufbar."},
  oComm:{fr:"Communautés",en:"Communities",es:"Comunidades",pt:"Comunidades",it:"Comunità",de:"Gemeinschaften"},
  videComm:{fr:"L'inverse des biorégions : au lieu de regrouper les cellules qui partagent des espèces, on regroupe les espèces qui partagent des cellules. Lance d'abord l'analyse des biorégions, dont cet onglet réutilise les données.",en:"The reverse of bioregions: instead of grouping cells that share species, it groups species that share cells. Run the bioregion analysis first — this tab reuses its data.",es:"Lo contrario de las biorregiones: en lugar de agrupar celdas que comparten especies, agrupa especies que comparten celdas. Ejecuta antes el análisis de biorregiones, cuyos datos reutiliza esta pestaña.",pt:"O inverso das biorregiões: em vez de agrupar células que partilham espécies, agrupa espécies que partilham células. Executa primeiro a análise de biorregiões, cujos dados esta aba reutiliza.",it:"L'inverso delle bioregioni: invece di raggruppare le celle che condividono specie, raggruppa le specie che condividono celle. Avvia prima l'analisi delle bioregioni, di cui questa scheda riusa i dati.",de:"Die Umkehrung der Bioregionen: statt Zellen mit gemeinsamen Arten werden Arten mit gemeinsamen Zellen gruppiert. Starte zuerst die Bioregionen-Analyse, deren Daten dieser Reiter nutzt."},
  commToutes:{fr:"Toutes",en:"All",es:"Todas",it:"Tutte",de:"Alle",pt:"Todas"},
  commPartTitre:{fr:"Part de la communauté dans cette biorégion, corrigée de l'effort d'observation : chaque effectif est rapporté au total observé dans la biorégion.",en:"Share of the community in this bioregion, corrected for observation effort: each count is divided by the total recorded in the bioregion.",es:"Parte de la comunidad en esta biorregión, corregida por el esfuerzo de observación: cada recuento se divide por el total observado en la biorregión.",pt:"Parte da comunidade nesta biorregião, corrigida do esforço de observação: cada contagem é dividida pelo total observado na biorregião.",it:"Quota della comunità in questa bioregione, corretta per lo sforzo di osservazione: ogni conteggio è diviso per il totale osservato nella bioregione.",de:"Anteil der Gemeinschaft in dieser Bioregion, bereinigt um den Beobachtungsaufwand: Jede Anzahl wird durch die Gesamtzahl der Beobachtungen der Bioregion geteilt."},
  commCarte:{fr:"Voir sa répartition",en:"See its distribution",es:"Ver su distribución",pt:"Ver a sua distribuição",it:"Vedi la sua distribuzione",de:"Verbreitung ansehen"},
  commPart:{fr:"Part des observations de la cellule appartenant à cette communauté",en:"Share of the cell's records belonging to this community",es:"Proporción de los registros de la celda que pertenecen a esta comunidad",pt:"Parcela dos registos da célula pertencentes a esta comunidade",it:"Quota delle segnalazioni della cella appartenenti a questa comunità",de:"Anteil der Nachweise der Zelle, die zu dieser Gemeinschaft gehören"},
  commAussi:{fr:"Aussi proche de : {0}",en:"Also close to: {0}",es:"También cercana a: {0}",pt:"Também próxima de: {0}",it:"Vicina anche a: {0}",de:"Ebenso nah an: {0}"},
  commTitre:{fr:"Communauté {0}",en:"Community {0}",es:"Comunidad {0}",pt:"Comunidade {0}",it:"Comunità {0}",de:"Gemeinschaft {0}"},
  commEsp:{fr:"{0} espèces",en:"{0} species",es:"{0} especies",pt:"{0} espécies",it:"{0} specie",de:"{0} Arten"},
  commPeu:{fr:"moins de {0} obs.",en:"fewer than {0} records",es:"menos de {0} registros",pt:"menos de {0} registos",it:"meno di {0} segnalazioni",de:"weniger als {0} Nachweise"},
  commAbsente:{fr:"absente de l'échantillon",en:"not in the sample",es:"ausente de la muestra",pt:"ausente da amostra",it:"assente dal campione",de:"nicht in der Stichprobe"},
  commRech:{fr:"Chercher une espèce…",en:"Search a species…",es:"Buscar una especie…",pt:"Procurar uma espécie…",it:"Cerca una specie…",de:"Art suchen…"},
  commTrouve:{fr:"appartient à la communauté {0}",en:"belongs to community {0}",es:"pertenece a la comunidad {0}",pt:"pertence à comunidade {0}",it:"appartiene alla comunità {0}",de:"gehört zur Gemeinschaft {0}"},
  commNote:{fr:"Les espèces sont regroupées selon les cellules qu'elles occupent, par classification hiérarchique (méthode de Ward). Une communauté rassemble des espèces qui se rencontrent aux mêmes endroits — ce qui traduit souvent un milieu partagé, parfois seulement des habitudes d'observation communes. La part par biorégion est corrigée de l'effort d'observation.",en:"Species are grouped by the cells they occupy, using hierarchical clustering (Ward's method). A community gathers species found in the same places — often reflecting a shared habitat, sometimes merely shared observer habits. The share per bioregion is corrected for observation effort.",es:"Las especies se agrupan según las celdas que ocupan, mediante clasificación jerárquica (método de Ward). Una comunidad reúne especies que se encuentran en los mismos lugares, lo que suele reflejar un hábitat común, a veces solo hábitos de observación compartidos. La parte por biorregión está corregida por el esfuerzo de observación.",pt:"As espécies são agrupadas segundo as células que ocupam, por classificação hierárquica (método de Ward). Uma comunidade reúne espécies encontradas nos mesmos locais, o que reflete muitas vezes um habitat partilhado, por vezes apenas hábitos de observação comuns. A parte por biorregião está corrigida do esforço de observação.",it:"Le specie sono raggruppate secondo le celle che occupano, con una classificazione gerarchica (metodo di Ward). Una comunità riunisce specie che si incontrano negli stessi luoghi, il che riflette spesso un ambiente condiviso, talvolta solo abitudini di osservazione comuni. La quota per bioregione è corretta per lo sforzo di osservazione.",de:"Arten werden nach den von ihnen besetzten Zellen gruppiert, mittels hierarchischer Clusteranalyse (Ward-Verfahren). Eine Gemeinschaft vereint Arten, die an denselben Orten vorkommen — oft ein gemeinsamer Lebensraum, manchmal nur gemeinsame Beobachtungsgewohnheiten. Der Anteil je Bioregion ist um den Beobachtungsaufwand bereinigt."},
  oBio:{fr:"Biorégions",en:"Bioregions",es:"Biorregiones",pt:"Biorregiões",it:"Bioregioni",de:"Bioregionen"},
  videBio:{fr:"Analyse exploratoire : découpe la zone en cellules et les regroupe selon la composition de leur faune ou de leur flore.",en:"Exploratory analysis: divides the area into cells and groups them by the composition of their species.",es:"Análisis exploratorio: divide la zona en celdas y las agrupa según la composición de sus especies.",pt:"Análise exploratória: divide a zona em células e agrupa-as segundo a composição das suas espécies.",it:"Analisi esplorativa: divide la zona in celle e le raggruppa secondo la composizione delle loro specie.",de:"Explorative Analyse: teilt das Gebiet in Zellen und gruppiert sie nach ihrer Artenzusammensetzung."},
  bioDuree:{fr:"L'analyse collecte plusieurs milliers d'observations : compte quelques minutes.",en:"The analysis collects several thousand records: allow a few minutes.",es:"El análisis recoge varios miles de registros: cuenta con unos minutos.",pt:"A análise recolhe vários milhares de registos: conta com alguns minutos.",it:"L'analisi raccoglie diverse migliaia di segnalazioni: conta qualche minuto.",de:"Die Analyse sammelt mehrere tausend Nachweise: rechne mit einigen Minuten."},
  lancerRecherche:{fr:"Lancer la recherche",en:"Run the search",es:"Iniciar la búsqueda",pt:"Iniciar a pesquisa",it:"Avvia la ricerca",de:"Suche starten"},
  coutRequetes:{fr:"environ {0} requêtes",en:"about {0} requests",es:"unas {0} peticiones",pt:"cerca de {0} pedidos",it:"circa {0} richieste",de:"etwa {0} Abfragen"},
  bioCharger:{fr:"Charger les données",en:"Load the data",es:"Cargar los datos",pt:"Carregar os dados",it:"Carica i dati",de:"Daten laden"},
  bioLancer:{fr:"Lancer l'analyse",en:"Run the analysis",es:"Ejecutar el análisis",pt:"Executar a análise",it:"Avvia l'analisi",de:"Analyse starten"},
  bioCharge:{fr:"Collecte des observations : {0}",en:"Collecting records: {0}",es:"Recogida de observaciones: {0}",pt:"Recolha de observações: {0}",it:"Raccolta delle osservazioni: {0}",de:"Sammle Nachweise: {0}"},
  bioCalcul:{fr:"Calcul en cours…",en:"Computing…",es:"Calculando…",pt:"A calcular…",it:"Calcolo in corso…",de:"Berechnung läuft…"},
  bioMaigre:{fr:"Pas assez d'observations localisées pour dégager des groupes. Essaie une zone plus vaste ou un groupe taxonomique plus fourni.",en:"Not enough located records to reveal groups. Try a wider area or a richer taxonomic group.",es:"No hay suficientes registros localizados para revelar grupos. Prueba una zona más amplia o un grupo taxonómico más rico.",pt:"Não há registos localizados suficientes para revelar grupos. Tenta uma zona mais ampla ou um grupo taxonómico mais rico.",it:"Non ci sono abbastanza segnalazioni localizzate per far emergere gruppi. Prova una zona più ampia o un gruppo più ricco.",de:"Zu wenige verortete Nachweise für Gruppen. Versuche ein größeres Gebiet oder eine artenreichere Gruppe."},
  bioResume:{fr:"{0} cellules retenues sur {1} observations · {2} espèces",en:"{0} cells kept from {1} records · {2} species",es:"{0} celdas retenidas de {1} registros · {2} especies",pt:"{0} células retidas de {1} registos · {2} espécies",it:"{0} celle mantenute su {1} segnalazioni · {2} specie",de:"{0} Zellen aus {1} Nachweisen · {2} Arten"},
  bioGroupe:{fr:"Groupe {0}",en:"Group {0}",es:"Grupo {0}",pt:"Grupo {0}",it:"Gruppo {0}",de:"Gruppe {0}"},
  bioCellules:{fr:"{0} cellules",en:"{0} cells",es:"{0} celdas",pt:"{0} células",it:"{0} celle",de:"{0} Zellen"},
  fermer:{fr:"Fermer",en:"Close",es:"Cerrar",pt:"Fechar",it:"Chiudi",de:"Schließen"},
  bioTout:{fr:"Tout",en:"Everything",es:"Todo",pt:"Tudo",it:"Tutto",de:"Alles"},
  bioRapide:{fr:"Rapide",en:"Quick",es:"Rápido",pt:"Rápido",it:"Rapido",de:"Schnell"},
  bioMoyen:{fr:"Moyen",en:"Medium",es:"Medio",pt:"Médio",it:"Medio",de:"Mittel"},
  bioFin:{fr:"Fin",en:"Fine",es:"Fino",pt:"Fino",it:"Fine",de:"Fein"},
  bioDetail:{fr:"{0} observations, environ {1}",en:"{0} records, about {1}",es:"{0} registros, unos {1}",pt:"{0} registos, cerca de {1}",it:"{0} osservazioni, circa {1}",de:"{0} Nachweise, etwa {1}"},
  bioSec:{fr:"{0} s",en:"{0} s",es:"{0} s",pt:"{0} s",it:"{0} s",de:"{0} s"},
  bioMin:{fr:"{0} min",en:"{0} min",es:"{0} min",pt:"{0} min",it:"{0} min",de:"{0} Min."},
  bioRecadrer:{fr:"Recadrer",en:"Reframe",es:"Reencuadrar",pt:"Reenquadrar",it:"Inquadra",de:"Neu ausrichten"},
  bioRecollecter:{fr:"Recollecter les données",en:"Collect data again",es:"Recoger los datos de nuevo",pt:"Recolher os dados de novo",it:"Raccogli di nuovo i dati",de:"Daten neu sammeln"},
  bioCache:{fr:"données en mémoire",en:"data from memory",es:"datos en memoria",pt:"dados em memória",it:"dati in memoria",de:"Daten aus dem Speicher"},
  bioK:{fr:"Groupes",en:"Groups",es:"Grupos",pt:"Grupos",it:"Gruppi",de:"Gruppen"},
  bioIndic:{fr:"Espèces caractéristiques",en:"Characteristic species",es:"Especies características",pt:"Espécies características",it:"Specie caratteristiche",de:"Kennzeichnende Arten"},
  bioPlafond:{fr:"Plafond de 10 000 observations atteint : l'analyse porte sur les plus récentes.",en:"Cap of 10,000 records reached: the analysis covers the most recent ones.",es:"Límite de 10 000 registros alcanzado: el análisis cubre los más recientes.",pt:"Limite de 10 000 registos atingido: a análise cobre os mais recentes.",it:"Limite di 10 000 segnalazioni raggiunto: l'analisi riguarda le più recenti.",de:"Obergrenze von 10 000 Nachweisen erreicht: Die Analyse umfasst die jüngsten."},
  bioNote:{fr:"Méthode : cellules d'au moins 2 km, composition normalisée par cellule puis passée au logarithme, analyse en composantes principales, regroupement de Ward. Les groupes reflètent en partie les habitudes des observateurs autant que l'écologie : restreins l'analyse à un groupe taxonomique pour limiter ce biais.",en:"Method: cells of at least 2 km, composition normalised per cell then log-transformed, principal component analysis, Ward clustering. The groups partly reflect observer habits as much as ecology: restrict the analysis to one taxonomic group to limit this bias.",es:"Método: celdas de al menos 2 km, composición normalizada por celda y transformada en logaritmo, análisis de componentes principales, agrupamiento de Ward. Los grupos reflejan en parte los hábitos de los observadores tanto como la ecología: restringe el análisis a un grupo taxonómico para limitar este sesgo.",pt:"Método: células de pelo menos 2 km, composição normalizada por célula e transformada em logaritmo, análise de componentes principais, agrupamento de Ward. Os grupos refletem em parte os hábitos dos observadores tanto quanto a ecologia: restringe a análise a um grupo taxonómico para limitar este viés.",it:"Metodo: celle di almeno 2 km, composizione normalizzata per cella e trasformata in logaritmo, analisi delle componenti principali, raggruppamento di Ward. I gruppi riflettono in parte le abitudini degli osservatori quanto l'ecologia: restringi l'analisi a un gruppo tassonomico per limitare questo bias.",de:"Methode: Zellen von mindestens 2 km, Zusammensetzung je Zelle normiert und logarithmiert, Hauptkomponentenanalyse, Ward-Clusterung. Die Gruppen spiegeln teils die Gewohnheiten der Beobachtenden ebenso wie die Ökologie: Beschränke die Analyse auf eine taxonomische Gruppe, um diesen Bias zu begrenzen."},
  arreter:{fr:"Arrêter",en:"Stop",es:"Detener",it:"Ferma",de:"Anhalten",pt:"Parar"},
  mArret:{fr:"Chargement interrompu.",en:"Loading stopped.",es:"Carga interrumpida.",it:"Caricamento interrotto.",de:"Laden abgebrochen.",pt:"Carregamento interrompido."},
  memTitre:{fr:"Inventaires en mémoire",en:"Saved inventories",es:"Inventarios en memoria",it:"Inventari in memoria",de:"Gespeicherte Inventare",pt:"Inventários em memória"},
  memVide:{fr:"Aucun inventaire enregistré.",en:"No saved inventory.",es:"Ningún inventario guardado.",it:"Nessun inventario salvato.",de:"Kein gespeichertes Inventar.",pt:"Nenhum inventário guardado."},
  memVoir:{fr:"Voir la mémoire",en:"View memory",es:"Ver la memoria",it:"Vedi la memoria",de:"Speicher ansehen",pt:"Ver a memória"},
  memOuvrir:{fr:"Ouvrir",en:"Open",es:"Abrir",it:"Apri",de:"Öffnen",pt:"Abrir"},
  memOublier:{fr:"Oublier",en:"Forget",es:"Olvidar",it:"Dimentica",de:"Vergessen",pt:"Esquecer"},
  memAncien:{fr:"enregistrement d'une version antérieure",en:"saved by an older version",es:"guardado por una versión anterior",it:"salvato da una versione precedente",de:"von einer älteren Version gespeichert",pt:"guardado por uma versão anterior"},
  touteAnnee:{fr:"Toute l'année",en:"All year",es:"Todo el año",it:"Tutto l'anno",de:"Ganzes Jahr",pt:"O ano inteiro"},
  cFond:{fr:"Fond",en:"Basemap",es:"Fondo",it:"Sfondo",de:"Karte",pt:"Base"},
  cpVoir:{fr:"Voir sur iNaturalist",en:"View on iNaturalist",es:"Ver en iNaturalist",it:"Vedi su iNaturalist",de:"Auf iNaturalist ansehen",pt:"Ver no iNaturalist"},
  cpGauche:{fr:"Déplacer à gauche",en:"Move left",es:"Mover a la izquierda",it:"Sposta a sinistra",de:"Nach links",pt:"Mover para a esquerda"},
  cpDroite:{fr:"Déplacer à droite",en:"Move right",es:"Mover a la derecha",it:"Sposta a destra",de:"Nach rechts",pt:"Mover para a direita"},
  cpRetirer:{fr:"Retirer",en:"Remove",es:"Quitar",it:"Rimuovi",de:"Entfernen",pt:"Remover"},
  oComparaison:{fr:"Comparaison",en:"Comparison",es:"Comparación",it:"Confronto",de:"Vergleich",pt:"Comparação"},
  videComparaison:{fr:"Ajoute des espèces depuis la liste, avec le bouton en forme de carré, pour les comparer ici côte à côte.",en:"Add species from the list with the square button to compare them side by side here.",es:"Añade especies desde la lista con el botón cuadrado para compararlas aquí lado a lado.",it:"Aggiungi specie dall'elenco con il pulsante quadrato per confrontarle qui affiancate.",de:"Füge Arten über die quadratische Schaltfläche aus der Liste hinzu, um sie hier nebeneinander zu vergleichen.",pt:"Adiciona espécies a partir da lista, com o botão quadrado, para as comparar aqui lado a lado."},
  cpAjouter:{fr:"Comparer cette espèce",en:"Compare this species",es:"Comparar esta especie",it:"Confronta questa specie",de:"Diese Art vergleichen",pt:"Comparar esta espécie"},
  cpVider:{fr:"Vider la liste",en:"Clear the list",es:"Vaciar la lista",it:"Svuota l'elenco",de:"Liste leeren",pt:"Limpar a lista"},
  cpToutes:{fr:"Toutes les photos",en:"All photos",es:"Todas las fotos",it:"Tutte le foto",de:"Alle Fotos",pt:"Todas as fotos"},
  cpLocal:{fr:"De la zone seulement",en:"From the area only",es:"Solo de la zona",it:"Solo dalla zona",de:"Nur aus dem Gebiet",pt:"Apenas da zona"},
  cpAucune:{fr:"Aucune photo pour ce filtre",en:"No photo for this filter",es:"Ninguna foto para este filtro",it:"Nessuna foto per questo filtro",de:"Kein Foto für diesen Filter",pt:"Nenhuma foto para este filtro"},
  cpNote:{fr:"Les annotations ne sont renseignées que sur une partie des observations : un filtre peut vider une colonne sans que l'espèce soit en cause.",en:"Annotations are filled in on only some observations: a filter may empty a column without the species being at fault.",es:"Las anotaciones solo constan en parte de las observaciones: un filtro puede vaciar una columna sin culpa de la especie.",pt:"As anotações só estão preenchidas numa parte das observações: um filtro pode esvaziar uma coluna sem culpa da espécie.",it:"Le annotazioni sono presenti solo su una parte delle osservazioni: un filtro può svuotare una colonna senza colpa della specie.",de:"Annotationen sind nur bei einem Teil der Beobachtungen vorhanden: Ein Filter kann eine Spalte leeren, ohne dass die Art schuld ist."},
  choisirCarte:{fr:"Choisir sur une carte",en:"Pick on a map",es:"Elegir en un mapa",it:"Scegli su una mappa",de:"Auf der Karte wählen",pt:"Escolher num mapa"},
  fermerCarte:{fr:"Fermer la carte",en:"Close the map",es:"Cerrar el mapa",it:"Chiudi la mappa",de:"Karte schließen",pt:"Fechar o mapa"},
  lieuxIci:{fr:"Lieux couvrant cette vue",en:"Places covering this view",es:"Lugares que cubren esta vista",it:"Luoghi che coprono questa vista",de:"Orte in diesem Ausschnitt",pt:"Lugares nesta vista"},
  aucunLieuIci:{fr:"Aucun lieu ici. Déplace ou dézoome la carte.",en:"No place here. Pan or zoom out.",es:"Ningún lugar aquí. Desplaza o aleja el mapa.",it:"Nessun luogo qui. Sposta o allarga la mappa.",de:"Kein Ort hier. Verschieben oder herauszoomen.",pt:"Nenhum lugar aqui. Desloca ou afasta o mapa."},
  maPosition:{fr:"Ma position",en:"My location",es:"Mi ubicación",it:"La mia posizione",de:"Mein Standort",pt:"A minha posição"},
  chercheLieux:{fr:"Recherche des lieux…",en:"Looking for places…",es:"Buscando lugares…",it:"Ricerca dei luoghi…",de:"Suche nach Orten…",pt:"Procurando lugares…"},
  auteur:{fr:"Site réalisé par Aubin Normand",en:"Built by Aubin Normand",es:"Sitio creado por Aubin Normand",it:"Sito realizzato da Aubin Normand",de:"Erstellt von Aubin Normand",pt:"Site criado por Aubin Normand"},
  triResp:{fr:"Par responsabilité",en:"By responsibility",es:"Por responsabilidad",it:"Per responsabilità",de:"Nach Verantwortung",pt:"Por responsabilidade"},
  triPic:{fr:"Les plus observées ce mois-ci",en:"Most recorded this month",es:"Las más observadas este mes",it:"Le più osservate questo mese",de:"Diesen Monat am häufigsten",pt:"As mais observadas neste mês"},
  mPret:{fr:"Liste prête : {0} espèces. Le reste se charge en arrière-plan.",
    en:"List ready: {0} species. The rest is loading in the background.",
    es:"Lista lista: {0} especies. El resto se carga en segundo plano.",
    it:"Elenco pronto: {0} specie. Il resto si carica in background.",
    de:"Liste bereit: {0} Arten. Der Rest lädt im Hintergrund.",
    pt:"Lista pronta: {0} espécies. O resto carrega em segundo plano."},
  aChercher:{fr:"À chercher en",en:"Look for in",es:"Buscar en",it:"Da cercare in",de:"Suchen im",pt:"Procurar em"},
  aChercherD:{fr:"Espèces dont c'est le pic d'observation",en:"Species peaking this month",es:"Especies en su pico este mes",it:"Specie al loro picco questo mese",de:"Arten mit ihrem Höhepunkt in diesem Monat",pt:"Espécies que atingem aqui o seu pico de observação"},
  aucunPic:{fr:"Aucune espèce ne culmine ce mois-ci.",en:"No species peaks this month.",es:"Ninguna especie culmina este mes.",it:"Nessuna specie culmina questo mese.",de:"Keine Art hat in diesem Monat ihren Höhepunkt.",pt:"Nenhuma espécie atinge o pico neste mês."},
  noteChercher:{fr:"Le pic est le mois où l'espèce cumule le plus d'observations dans la zone. Pour une plante c'est souvent la floraison, pour un insecte l'émergence, pour un oiseau le passage migratoire — mais c'est aussi, en partie, le moment où les gens la remarquent.",en:"The peak is the month with the most records in the area. For a plant it is usually flowering, for an insect emergence, for a bird migration — but it is also, in part, when people notice it.",es:"El pico es el mes con más registros en la zona. En una planta suele ser la floración, en un insecto la emergencia, en un ave el paso migratorio, pero también es, en parte, cuando la gente la nota.",it:"Il picco è il mese con più segnalazioni nella zona. Per una pianta è di solito la fioritura, per un insetto lo sfarfallamento, per un uccello il passo migratorio, ma è anche, in parte, quando la gente la nota.",de:"Der Höhepunkt ist der Monat mit den meisten Nachweisen im Gebiet. Bei Pflanzen meist die Blüte, bei Insekten der Schlupf, bei Vögeln der Durchzug — aber auch, teilweise, wann Menschen sie bemerken.",pt:"O pico é o mês em que a espécie acumula mais observações na zona. Numa planta é muitas vezes a floração, num inseto a emergência, numa ave a passagem migratória — mas é também, em parte, o momento em que as pessoas reparam nela."},
  r_superfamily:{fr:"super-famille",en:"superfamily",es:"superfamilia",it:"superfamiglia",de:"Überfamilie",pt:"superfamília"},
  oSaison:{fr:"Saisonnalité",en:"Seasonality",es:"Estacionalidad",it:"Stagionalità",de:"Saisonalität",pt:"Sazonalidade"},
  videSaison:{fr:"Cet onglet montre le rythme de l'année : quand sortir, et pour voir quoi.",
    en:"This tab shows the rhythm of the year: when to go out, and for what.",
    es:"Esta pestaña muestra el ritmo del año: cuándo salir y para ver qué.",
    it:"Questa scheda mostra il ritmo dell'anno: quando uscire e per vedere cosa.",
    de:"Dieser Reiter zeigt den Jahresrhythmus: wann hinausgehen und wofür.",
    pt:"Este separador mostra o ritmo do ano: quando sair, e para ver o quê."},
  legPicMois:{fr:"Espèces à leur pic",en:"Species at their peak",es:"Especies en su pico",pt:"Espécies no seu pico",it:"Specie al loro picco",de:"Arten im Maximum"},
}).forEach(([k, v]) => { for (const l in v) TEXTES[l][k] = v[l]; });

const LANGUES = { fr:'Français', en:'English', es:'Español', pt:'Português', it:'Italiano', de:'Deutsch' };

function langueInitiale() {
  try {
    const m = new URLSearchParams(location.search).get('lang');
    if (m && LANGUES[m]) return m;
    const g = localStorage.getItem('langue');
    if (g && LANGUES[g]) return g;
  } catch (e) { /* navigation privée : on retombe sur la langue du navigateur */ }
  const n = String(navigator.language || 'fr').slice(0, 2).toLowerCase();
  return LANGUES[n] ? n : 'fr';
}

let langue = langueInitiale();

/* Traduction. Les valeurs peuvent contenir des marqueurs {0}, {1}… remplacés par les
   arguments passés à l'appel. Une clé inconnue se renvoie elle-même, ce qui la rend visible
   à l'écran plutôt que de laisser un vide. */
const t = (cle, ...v) => {
  let x = (TEXTES[langue] && TEXTES[langue][cle]) || TEXTES.en[cle] || cle;
  v.forEach((val, i) => { x = x.replace('{' + i + '}', val); });
  return x;
};

const MOIS_L = {
  fr:['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],
  en:['January','February','March','April','May','June','July','August','September','October','November','December'],
  es:['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
  it:['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'],
  de:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  pt:['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro']
};
let MOIS = MOIS_L[langue] || MOIS_L.en;

/* Tronquer à trois lettres donne « jui » pour juin comme pour juillet : les abréviations
   sont donc écrites, langue par langue. */
const MOIS_C_L = {
  fr:['janv','févr','mars','avr','mai','juin','juil','août','sept','oct','nov','déc'],
  en:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  es:['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'],
  it:['gen','feb','mar','apr','mag','giu','lug','ago','set','ott','nov','dic'],
  de:['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],
  pt:['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez']
};
let MOIS_C = MOIS_C_L[langue] || MOIS_C_L.en;

/* Applique les traductions au document : texte pour data-t, invite de saisie pour data-tp,
   infobulle pour data-tt — ce dernier laissant le contenu de l'élément intact, ce qui permet
   de traduire un bouton réduit à une icône. */
function traduire() {
  document.documentElement.lang = langue;
  document.querySelectorAll('[data-t]').forEach(el => {
    const v = t(el.dataset.t); if (v) el.textContent = v;
  });
  document.querySelectorAll('[data-tp]').forEach(el => {
    const v = t(el.dataset.tp); if (v) el.placeholder = v;
  });
  document.querySelectorAll('[data-tt]').forEach(el => {
    const v = t(el.dataset.tt);
    if (v) { el.title = v; el.setAttribute('aria-label', v); }
  });
}

/* Changement de langue sans rechargement. Les textes du site basculent aussitôt ; seuls les
   noms vernaculaires viennent d'iNaturalist et doivent être redemandés — et uniquement si
   l'affichage les utilise. */
async function changerLangue(l) {
  if (!LANGUES[l] || l === langue) return;
  langue = l;
  try { localStorage.setItem('langue', l); } catch (e) { /* sans effet en navigation privée */ }

  MOIS = MOIS_L[l] || MOIS_L.en;
  MOIS_C = MOIS_C_L[l] || MOIS_C_L.en;
  traduire();

  majURL();

  // Les réponses en cache portent l'ancienne langue dans leur adresse : elles sont caduques.
  cache.clear();
  oublier();          // chaque module jette ce qu'il gardait dans l'ancienne langue

  if (!etat.especes.length) return;
  if (vue.nommage === 'sci') { redessinerTout(); return; }
  enTache(rafraichirNoms);
}

/* Ne récupère que les noms vernaculaires, par lots de deux cents taxons : environ sept
   requêtes pour un inventaire de mille quatre cents espèces, contre une cinquantaine pour
   un rechargement complet. */
async function rafraichirNoms() {
  const gen = generation;
  const ids = [...new Set([...etat.especes.map(e => e.id), ...etat.ancetres.keys()])];
  const parId = new Map(etat.especes.map(e => [e.id, e]));

  try {
    for (let i = 0; i < ids.length; i += 200) {
      progression(t('mNoms', Math.min(i + 200, ids.length), ids.length),
        (i / ids.length) * 100);
      const d = await appel('/taxa', { id: ids.slice(i, i + 200).join(','),
        per_page:200, locale:langue });
      verifier(gen);
      (d.results || []).forEach(x => {
        const nom = x.preferred_common_name || '';
        const e = parId.get(x.id);
        if (e) e.nomFr = nom;
        const a = etat.ancetres.get(x.id);
        if (a) a.nomFr = nom;
      });
    }
    redessinerTout();
    enregistrer();
    progression(t('mComplet'), null);
  } catch (e) {
    if (!(e instanceof Annule)) progression(t('mEchec', String((e && e.message) || e)), null);
  }
}


/* Noms des trois outils. « Coche » ne se traduit pas mot à mot : chaque langue reçoit le
   terme que ses naturalistes emploient pour les espèces pas encore vues — « lifers » en
   anglais —, ou à défaut une formule courte qui dit la même chose. */
Object.entries({
  chargeEnCours:{fr:"Chargement en cours",en:"Loading",es:"Cargando",it:"Caricamento in corso",de:"Wird geladen",pt:"A carregar"},
  chargeEnCoursD:{fr:"Le nouvel inventaire se charge. Cet onglet se remplira dès qu'il sera prêt.",en:"The new inventory is loading. This tab will fill in as soon as it is ready.",es:"El nuevo inventario se está cargando. Esta pestaña se llenará en cuanto esté listo.",it:"Il nuovo inventario si sta caricando. Questa scheda si riempirà appena sarà pronto.",de:"Das neue Inventar wird geladen. Dieser Reiter füllt sich, sobald es bereit ist.",pt:"O novo inventário está a carregar. Este separador vai preencher-se assim que estiver pronto."},
  outilIci:{fr:"Exploration", en:"Exploration", es:"Exploración", it:"Esplorazione", de:"Erkundung", pt:"Exploração"},
  outilQuoi:{fr:"Identification", en:"Identification", es:"Identificación", it:"Identificazione", de:"Bestimmung", pt:"Identificação"},
  outilCoche:{fr:"Coche", en:"Lifers", es:"Por ver", it:"Da vedere", de:"Neue Arten", pt:"Por ver"},
  titreIci:{fr:"Exploration · Cequivitici", en:"Exploration · Cequivitici", es:"Exploración · Cequivitici", it:"Esplorazione · Cequivitici", de:"Erkundung · Cequivitici", pt:"Exploração · Cequivitici"},
  titreQuoi:{fr:"Identification · Cequivitici", en:"Identification · Cequivitici", es:"Identificación · Cequivitici", it:"Identificazione · Cequivitici", de:"Bestimmung · Cequivitici", pt:"Identificação · Cequivitici"},
  titreCoche:{fr:"Coche · Cequivitici", en:"Lifers · Cequivitici", es:"Por ver · Cequivitici", it:"Da vedere · Cequivitici", de:"Neue Arten · Cequivitici", pt:"Por ver · Cequivitici"},
}).forEach(([k, v]) => { for (const l in v) TEXTES[l][k] = v[l]; });

/* Ajouts tardifs : la fenêtre glissante, commune aux trois outils. */
Object.entries({
  pFenetreOpt:{fr:"Maintenant ({0} → {1})", en:"Right now ({0} → {1})",
    es:"Ahora ({0} → {1})", pt:"Agora ({0} → {1})", it:"Adesso ({0} → {1})",
    de:"Jetzt ({0} → {1})"},
  oter:{fr:"Retirer", en:"Remove", es:"Quitar", it:"Rimuovi", de:"Entfernen", pt:"Remover"},
  deplier:{fr:"Déplier ou replier", en:"Expand or collapse", es:"Desplegar o plegar",
    it:"Espandi o comprimi", de:"Auf- oder zuklappen", pt:"Expandir ou recolher"},
  grapheMensuel:{fr:"Observations et nombre d'espèces mois par mois", en:"Records and number of species month by month",
    es:"Observaciones y número de especies mes a mes", it:"Osservazioni e numero di specie mese per mese",
    de:"Beobachtungen und Artenzahl Monat für Monat", pt:"Observações e número de espécies mês a mês"},
  cValidees:{fr:"observations validées", en:"research-grade records", es:"observaciones validadas",
    it:"osservazioni validate", de:"bestätigte Beobachtungen", pt:"observações validadas"},
  cToutesObs:{fr:"toutes les observations", en:"all records", es:"todas las observaciones",
    it:"tutte le osservazioni", de:"alle Beobachtungen", pt:"todas as observações"},
  pFenetreOptDate:{fr:"Autour de la date choisie ({0} → {1})", en:"Around the chosen date ({0} → {1})",
    es:"En torno a la fecha elegida ({0} → {1})", pt:"Em torno da data escolhida ({0} → {1})",
    it:"Intorno alla data scelta ({0} → {1})", de:"Um das gewählte Datum ({0} → {1})"},
  pFenetreNom:{fr:"les quatre semaines du {0} au {1}", en:"the four weeks from {0} to {1}",
    es:"las cuatro semanas del {0} al {1}", pt:"as quatro semanas de {0} a {1}",
    it:"le quattro settimane dal {0} al {1}", de:"die vier Wochen vom {0} bis {1}"},
  mFenetre:{fr:"Observations des quatre semaines autour d'aujourd'hui…",
    en:"Records from the four weeks around today…",
    es:"Registros de las cuatro semanas alrededor de hoy…",
    pt:"Registos das quatro semanas em torno de hoje…",
    it:"Segnalazioni delle quattro settimane intorno a oggi…",
    de:"Nachweise der vier Wochen um heute…"},
  pFenetreIndispo:{
    fr:"L'API n'a pas appliqué le filtre par semaine : la fenêtre est indisponible, choisis un mois.",
    en:"The API did not apply the week filter: the window is unavailable, pick a month.",
    es:"La API no aplicó el filtro por semana: la ventana no está disponible, elige un mes.",
    pt:"A API não aplicou o filtro por semana: a janela está indisponível, escolhe um mês.",
    it:"L'API non ha applicato il filtro per settimana: la finestra non è disponibile, scegli un mese.",
    de:"Die API hat den Wochenfilter nicht angewandt: Das Fenster ist nicht verfügbar, wähle einen Monat."}
}).forEach(([k, v]) => { for (const l in v) TEXTES[l][k] = v[l]; });
