/* ============================================================
   Textes propres à l'outil Identification
   ============================================================ */

/* Le tronc commun est dans commun/textes.js ; seules les clés que cet outil est seul à
   utiliser sont ici, greffées sur la même table, dans les six langues du site. Une clé
   ajoutée plus tard dans une seule langue retombe sur l'anglais : la page reste cohérente
   plutôt que d'afficher des clés brutes. */

Object.entries({
  sousQuoi:{
    fr:"Des espèces probables à la bonne réponse : ce qui vit là où tu as observé, les confusions possibles et les critères pour trancher.",
    en:"From likely species to the right answer: what lives where you made your observation, the possible look-alikes and the criteria to decide.",
    es:"De las especies probables a la respuesta correcta: lo que vive donde observaste, las posibles confusiones y los criterios para decidir.",
    it:"Dalle specie probabili alla risposta giusta: cosa vive dove hai osservato, le possibili confusioni e i criteri per decidere.",
    de:"Von den wahrscheinlichen Arten zur richtigen Antwort: was dort lebt, wo du beobachtet hast, mögliche Verwechslungen und die Merkmale, die entscheiden.",
    pt:"Das espécies prováveis à resposta certa: o que vive onde observaste, as confusões possíveis e os critérios para decidir."},

  oCandidats:{fr:"Candidats", en:"Candidates", es:"Candidatos", it:"Candidati", de:"Kandidaten", pt:"Candidatos"},
  videCandidats:{
    fr:"Les espèces plausibles ici à cette période, classées par fréquence d'observation.",
    en:"The species plausible here for this period, ranked by observation frequency.",
    es:"Las especies plausibles aquí en este periodo, ordenadas por frecuencia de observación.",
    it:"Le specie plausibili qui in questo periodo, ordinate per frequenza di osservazione.",
    de:"Die hier in diesem Zeitraum plausiblen Arten, sortiert nach Beobachtungshäufigkeit.",
    pt:"As espécies plausíveis aqui neste período, ordenadas por frequência de observação."},

  qAttente:{fr:"Chargement de la période en cours…", en:"Loading this time window…", es:"Cargando el periodo…", it:"Caricamento del periodo in corso…", de:"Zeitraum wird geladen…", pt:"A carregar o período…"},
  qFenetreIndispo:{fr:"Période indisponible", en:"Time window unavailable", es:"Periodo no disponible", it:"Periodo non disponibile", de:"Zeitraum nicht verfügbar", pt:"Período indisponível"},
  qFenetreIndispoD:{
    fr:"Les observations de cette période n'ont pas pu être chargées. Réessaie plus tard, ou choisis une autre période.",
    en:"Records for this period could not be loaded. Try again later, or pick another period.",
    es:"No se han podido cargar las observaciones de este periodo. Vuelve a intentarlo más tarde o elige otro periodo.",
    it:"Non è stato possibile caricare le osservazioni di questo periodo. Riprova più tardi, o scegli un altro periodo.",
    de:"Die Beobachtungen dieses Zeitraums konnten nicht geladen werden. Versuch es später erneut oder wähle einen anderen Zeitraum.",
    pt:"Não foi possível carregar as observações deste período. Tenta mais tarde ou escolhe outro período."},
  qRien:{fr:"Rien à cette période", en:"Nothing for this period", es:"Nada en este periodo", it:"Niente in questo periodo", de:"Nichts in diesem Zeitraum", pt:"Nada neste período"},
  qRienD:{
    fr:"Aucune espèce du groupe choisi n'a été observée ici pendant cette période. Élargis le groupe, le lieu ou la période.",
    en:"No species from the chosen group was recorded here during this period. Widen the group, the place, or the period.",
    es:"No se ha observado aquí ninguna especie del grupo elegido durante este periodo. Amplía el grupo, el lugar o el periodo.",
    it:"Nessuna specie del gruppo scelto è stata osservata qui in questo periodo. Allarga il gruppo, il luogo o il periodo.",
    de:"Keine Art der gewählten Gruppe wurde hier in diesem Zeitraum beobachtet. Erweitere Gruppe, Ort oder Zeitraum.",
    pt:"Nenhuma espécie do grupo escolhido foi observada aqui neste período. Alarga o grupo, o lugar ou o período."},
  qNote:{fr:"{0} · {1} observations au total.", en:"{0} · {1} records in total.", es:"{0} · {1} observaciones en total.", it:"{0} · {1} osservazioni in totale.", de:"{0} · {1} Beobachtungen insgesamt.", pt:"{0} · {1} observações no total."},
  qBiais:{
    fr:"À garder en tête : la fréquence d'observation n'est pas la fréquence des individus. Les espèces spectaculaires, diurnes et faciles à photographier sont massivement sur-représentées.",
    en:"Keep in mind: observation frequency is not the frequency of individuals. Spectacular, diurnal and easy-to-photograph species are massively over-represented.",
    es:"Tenlo en cuenta: la frecuencia de observación no es la frecuencia de individuos. Las especies llamativas, diurnas y fáciles de fotografiar están muy sobrerrepresentadas.",
    it:"Da tenere a mente: la frequenza di osservazione non è la frequenza degli individui. Le specie spettacolari, diurne e facili da fotografare sono fortemente sovrarappresentate.",
    de:"Bedenke: Beobachtungshäufigkeit ist nicht Individuenhäufigkeit. Auffällige, tagaktive und leicht zu fotografierende Arten sind stark überrepräsentiert.",
    pt:"A ter em conta: a frequência de observação não é a frequência dos indivíduos. As espécies vistosas, diurnas e fáceis de fotografar estão fortemente sobrerrepresentadas."},
  qPartTitre:{fr:"{0} observations · {1}", en:"{0} records · {1}", es:"{0} observaciones · {1}", it:"{0} osservazioni · {1}", de:"{0} Beobachtungen · {1}", pt:"{0} observações · {1}"},
  qCandidats:{fr:"candidats", en:"candidates", es:"candidatos", it:"candidati", de:"Kandidaten", pt:"candidatos"},
  qComparer:{fr:"Comparer", en:"Compare", es:"Comparar", it:"Confronta", de:"Vergleichen", pt:"Comparar"},

  cpPanier:{fr:"Retenues", en:"Selected", es:"Seleccionadas", it:"Selezionate", de:"Ausgewählt", pt:"Retidas"},

  acOui:{fr:"De saison · {0} obs. sur la période", en:"In season · {0} records in this period", es:"De temporada · {0} obs. en el periodo", it:"Di stagione · {0} oss. nel periodo", de:"Saisonal passend · {0} Beob. im Zeitraum", pt:"Da época · {0} obs. no período"},
  acPeu:{fr:"Peu vue à cette période · {0} obs.", en:"Rarely seen in this period · {0} records", es:"Poco vista en este periodo · {0} obs.", it:"Poco vista in questo periodo · {0} oss.", de:"In diesem Zeitraum selten gesehen · {0} Beob.", pt:"Pouco vista neste período · {0} obs."},
  acNon:{fr:"Jamais vue ici à cette période", en:"Never recorded here in this period", es:"Nunca vista aquí en este periodo", it:"Mai vista qui in questo periodo", de:"Hier in diesem Zeitraum nie gesehen", pt:"Nunca vista aqui neste período"},
  acTitre:{
    fr:"Période choisie dans l'onglet Candidats ({0}) : {1} observations dans la zone sur {2} au total, soit {3} %. « De saison » à partir de 5 %.",
    en:"Period chosen in the Candidates tab ({0}): {1} records in the area out of {2} in total, i.e. {3} %. “In season” from 5 %.",
    es:"Periodo elegido en la pestaña Candidatos ({0}): {1} observaciones en la zona de {2} en total, es decir, un {3} %. «De temporada» a partir del 5 %.",
    it:"Periodo scelto nella scheda Candidati ({0}): {1} osservazioni nella zona su {2} in totale, cioè il {3} %. «Di stagione» dal 5 %.",
    de:"Im Reiter Kandidaten gewählter Zeitraum ({0}): {1} Beobachtungen im Gebiet von insgesamt {2}, also {3} %. „Saisonal passend“ ab 5 %.",
    pt:"Período escolhido no separador Candidatos ({0}): {1} observações na zona de {2} no total, ou seja {3} %. «Da época» a partir de 5 %."},

  oConfusions:{fr:"Confusions", en:"Look-alikes", es:"Confusiones", it:"Confusioni", de:"Verwechslungen", pt:"Confusões"},
  videConfusions:{
    fr:"Les espèces avec lesquelles chaque candidat retenu est le plus souvent confondu, et depuis quelle source.",
    en:"The species each selected candidate is most often confused with, and from which source.",
    es:"Las especies con las que más a menudo se confunde cada candidato seleccionado, y de qué fuente sale el dato.",
    it:"Le specie con cui ogni candidato selezionato viene confuso più spesso, e da quale fonte.",
    de:"Die Arten, mit denen jeder ausgewählte Kandidat am häufigsten verwechselt wird, und aus welcher Quelle.",
    pt:"As espécies com que cada candidato retido é mais vezes confundido, e segundo que fonte."},
  cfSansPanier:{fr:"Aucune espèce retenue", en:"No species selected", es:"Ninguna especie seleccionada", it:"Nessuna specie selezionata", de:"Keine Art ausgewählt", pt:"Nenhuma espécie retida"},
  cfSansPanierD:{
    fr:"Retiens au moins un candidat depuis l'onglet Candidats pour voir ses confusions possibles.",
    en:"Select at least one candidate from the Candidates tab to see its possible confusions.",
    es:"Selecciona al menos un candidato en la pestaña Candidatos para ver sus posibles confusiones.",
    it:"Seleziona almeno un candidato dalla scheda Candidati per vedere le sue possibili confusioni.",
    de:"Wähle im Reiter Kandidaten mindestens einen Kandidaten aus, um mögliche Verwechslungen zu sehen.",
    pt:"Retém pelo menos um candidato no separador Candidatos para ver as suas confusões possíveis."},
  cfAttente:{fr:"Recherche des confusions en cours…", en:"Looking for possible confusions…", es:"Buscando confusiones…", it:"Ricerca delle confusioni in corso…", de:"Suche nach Verwechslungen…", pt:"A procurar confusões…"},
  cfAvec:{fr:"Confusions avec {0}", en:"Confused with {0}", es:"Confusiones con {0}", it:"Confusioni con {0}", de:"Verwechslungen mit {0}", pt:"Confusões com {0}"},
  cfAucune:{fr:"Aucune confusion connue pour cette espèce.", en:"No known confusion for this species.", es:"No se conoce ninguna confusión para esta especie.", it:"Nessuna confusione nota per questa specie.", de:"Keine bekannte Verwechslung für diese Art.", pt:"Nenhuma confusão conhecida para esta espécie."},
  cfForce:{fr:"{0} corrections", en:"{0} corrections", es:"{0} correcciones", it:"{0} correzioni", de:"{0} Korrekturen", pt:"{0} correções"},
  cfPresente:{fr:"Présente dans la zone", en:"Present in the area", es:"Presente en la zona", it:"Presente nella zona", de:"Im Gebiet vorhanden", pt:"Presente na zona"},
  cfAbsente:{fr:"Absente de la zone", en:"Not in the area", es:"Ausente de la zona", it:"Assente dalla zona", de:"Nicht im Gebiet", pt:"Ausente da zona"},
  cfIciTotal:{fr:"{0} obs. dans la zone, toutes dates", en:"{0} records in the area, all dates", es:"{0} obs. en la zona, todas las fechas", it:"{0} oss. nella zona, tutte le date", de:"{0} Beob. im Gebiet, alle Daten", pt:"{0} obs. na zona, todas as datas"},
  cfGroupePresentes:{fr:"Présentes dans la zone", en:"Present in the area", es:"Presentes en la zona", it:"Presenti nella zona", de:"Im Gebiet vorhanden", pt:"Presentes na zona"},
  cfGroupePresentesD:{
    fr:"Déjà observées dans la zone chargée : ce sont les confusions qui te concernent vraiment.",
    en:"Already recorded in the loaded area: these are the confusions that really matter to you.",
    es:"Ya observadas en la zona cargada: son las confusiones que de verdad te afectan.",
    it:"Già osservate nella zona caricata: sono le confusioni che ti riguardano davvero.",
    de:"Bereits im geladenen Gebiet beobachtet: Diese Verwechslungen betreffen dich wirklich.",
    pt:"Já observadas na zona carregada: são as confusões que realmente te dizem respeito."},
  cfGroupeAbsentes:{fr:"Absentes de la zone", en:"Not in the area", es:"Ausentes de la zona", it:"Assenti dalla zona", de:"Nicht im Gebiet", pt:"Ausentes da zona"},
  cfGroupeAbsentesD:{
    fr:"Jamais observées dans la zone chargée. Elles se confondent ailleurs, mais ici on peut en principe les écarter.",
    en:"Never recorded in the loaded area. They get confused elsewhere, but here they can in principle be ruled out.",
    es:"Nunca observadas en la zona cargada. Se confunden en otros lugares, pero aquí en principio se pueden descartar.",
    it:"Mai osservate nella zona caricata. Vengono confuse altrove, ma qui in linea di principio si possono escludere.",
    de:"Im geladenen Gebiet nie beobachtet. Anderswo werden sie verwechselt, hier lassen sie sich im Prinzip ausschließen.",
    pt:"Nunca observadas na zona carregada. Confundem-se noutros sítios, mas aqui podem, em princípio, ser afastadas."},
  cfAucunePresente:{
    fr:"Aucune des confusions connues n'a été observée dans la zone.",
    en:"None of the known look-alikes has been recorded in the area.",
    es:"Ninguna de las confusiones conocidas se ha observado en la zona.",
    it:"Nessuna delle confusioni note è stata osservata nella zona.",
    de:"Keine der bekannten Verwechslungen wurde im Gebiet beobachtet.",
    pt:"Nenhuma das confusões conhecidas foi observada na zona."},
  cfPic:{fr:"Pic en {0} ({1} %)", en:"Peaks in {0} ({1}%)", es:"Pico en {0} ({1} %)", it:"Picco a {0} ({1} %)", de:"Höhepunkt im {0} ({1} %)", pt:"Pico em {0} ({1} %)"},
  cfComparer:{fr:"Comparer", en:"Compare", es:"Comparar", it:"Confronta", de:"Vergleichen", pt:"Comparar"},
  cfRetirer:{fr:"Retirer", en:"Remove", es:"Quitar", it:"Rimuovi", de:"Entfernen", pt:"Retirar"},

  oCriteres:{fr:"Critères", en:"Criteria", es:"Criterios", it:"Criteri", de:"Merkmale", pt:"Critérios"},
  videCriteres:{
    fr:"Les critères que les déterminateurs eux-mêmes ont écrits, pour chaque candidat retenu.",
    en:"The criteria the identifiers themselves wrote, for each selected candidate.",
    es:"Los criterios que escribieron los propios identificadores, para cada candidato seleccionado.",
    it:"I criteri scritti dagli stessi identificatori, per ogni candidato selezionato.",
    de:"Die Merkmale, die die Bestimmenden selbst notiert haben, für jeden ausgewählten Kandidaten.",
    pt:"Os critérios escritos pelos próprios identificadores, para cada candidato retido."},
  crSansPanier:{fr:"Aucune espèce retenue", en:"No species selected", es:"Ninguna especie seleccionada", it:"Nessuna specie selezionata", de:"Keine Art ausgewählt", pt:"Nenhuma espécie retida"},
  crSansPanierD:{
    fr:"Retiens au moins un candidat depuis l'onglet Candidats pour lire ses critères.",
    en:"Select at least one candidate from the Candidates tab to read its criteria.",
    es:"Selecciona al menos un candidato en la pestaña Candidatos para leer sus criterios.",
    it:"Seleziona almeno un candidato dalla scheda Candidati per leggerne i criteri.",
    de:"Wähle im Reiter Kandidaten mindestens einen Kandidaten aus, um seine Merkmale zu lesen.",
    pt:"Retém pelo menos um candidato no separador Candidatos para ler os seus critérios."},
  crAttente:{fr:"Lecture des identifications et des commentaires…", en:"Reading identifications and comments…", es:"Leyendo identificaciones y comentarios…", it:"Lettura delle identificazioni e dei commenti…", de:"Bestimmungen und Kommentare werden gelesen…", pt:"A ler identificações e comentários…"},
  crNotes:{fr:"{0} critères", en:"{0} criteria", es:"{0} criterios", it:"{0} criteri", de:"{0} Merkmale", pt:"{0} critérios"},
  crAucune:{fr:"Aucun critère trouvé", en:"No criteria found", es:"No se han encontrado criterios", it:"Nessun criterio trovato", de:"Keine Merkmale gefunden", pt:"Nenhum critério encontrado"},
  crAucuneD:{
    fr:"Personne n'a laissé de texte utile pour cette espèce, ici ou ailleurs.",
    en:"No one has left a useful note for this species, here or elsewhere.",
    es:"Nadie ha dejado un texto útil para esta especie, ni aquí ni en otro lugar.",
    it:"Nessuno ha lasciato un testo utile per questa specie, qui o altrove.",
    de:"Niemand hat zu dieser Art einen hilfreichen Text hinterlassen, weder hier noch anderswo.",
    pt:"Ninguém deixou texto útil para esta espécie, nem aqui nem noutro sítio."},
  crSource_id:{fr:"identification", en:"identification", es:"identificación", it:"identificazione", de:"Bestimmung", pt:"identificação"},
  crSource_com:{fr:"commentaire", en:"comment", es:"comentario", it:"commento", de:"Kommentar", pt:"comentário"},
  crSource_aide:{fr:"aide à l'identification", en:"ID tip", es:"ayuda a la identificación", it:"aiuto all'identificazione", de:"Bestimmungshilfe", pt:"ajuda à identificação"},
  crAideNominee:{fr:"Aide à l'identification nominée sur iNaturalist", en:"Nominated as an ID tip on iNaturalist", es:"Nominada como ayuda a la identificación en iNaturalist", it:"Aiuto all'identificazione nominato su iNaturalist", de:"Auf iNaturalist als Bestimmungshilfe nominiert", pt:"Ajuda à identificação nomeada no iNaturalist"},
  crVotes:{fr:"{0} vote(s)", en:"{0} vote(s)", es:"{0} voto(s)", it:"{0} voto/i", de:"{0} Stimme(n)", pt:"{0} voto(s)"},
  crAides:{fr:"Aides à l'identification nominées", en:"Nominated ID tips", es:"Ayudas a la identificación nominadas", it:"Aiuti all'identificazione nominati", de:"Nominierte Bestimmungshilfen", pt:"Ajudas à identificação nomeadas"},
  crPhMot:{fr:"Chercher un mot dans les critères (ex. aile, wing)…", en:"Search the criteria for a word (e.g. wing)…", es:"Buscar una palabra en los criterios (ej. ala, wing)…", it:"Cerca una parola nei criteri (es. ala, wing)…", de:"Wort in den Merkmalen suchen (z. B. Flügel, wing)…", pt:"Procurar uma palavra nos critérios (ex. asa, wing)…"},
  crTrouves:{fr:"{0} note(s) contenant ce mot", en:"{0} note(s) containing this word", es:"{0} nota(s) con esta palabra", it:"{0} nota/e con questa parola", de:"{0} Notiz(en) mit diesem Wort", pt:"{0} nota(s) com esta palavra"},
  crRienMot:{fr:"Aucune note ne contient « {0} ».", en:"No note contains “{0}”.", es:"Ninguna nota contiene «{0}».", it:"Nessuna nota contiene «{0}».", de:"Keine Notiz enthält „{0}“.", pt:"Nenhuma nota contém «{0}»."},
  crPlus:{fr:"Afficher les {0} autres", en:"Show the other {0}", es:"Mostrar las otras {0}", it:"Mostra le altre {0}", de:"Die übrigen {0} anzeigen", pt:"Mostrar as outras {0}"},
  cpPlus:{fr:"+ de photos", en:"More photos", es:"+ fotos", it:"+ foto", de:"+ Fotos", pt:"+ fotos"},
  doNbPhotos:{fr:"{0} photos", en:"{0} photos", es:"{0} fotos", it:"{0} foto", de:"{0} Fotos", pt:"{0} fotos"},
  doPhoto:{fr:"Photo {0} de l'observation", en:"Observation photo {0}", es:"Foto {0} de la observación", it:"Foto {0} dell'osservazione", de:"Foto {0} der Beobachtung", pt:"Foto {0} da observação"},
  doFlottant:{fr:"Mon observation · {0} photo(s)", en:"My observation · {0} photo(s)", es:"Mi observación · {0} foto(s)", it:"La mia osservazione · {0} foto", de:"Meine Beobachtung · {0} Foto(s)", pt:"A minha observação · {0} foto(s)"},
  doRayon:{fr:"Rayon du cercle autour du point", en:"Radius of the circle around the point", es:"Radio del círculo alrededor del punto", it:"Raggio del cerchio attorno al punto", de:"Radius des Kreises um den Punkt", pt:"Raio do círculo em torno do ponto"},
  doAutoOpt:{fr:"Rayon automatique", en:"Automatic radius", es:"Radio automático", it:"Raggio automatico", de:"Automatischer Radius", pt:"Raio automático"},
  doRayonAuto:{fr:"Cercle de {0} km de rayon, ajusté à la densité d'observations", en:"{0} km radius circle, adjusted to observation density", es:"Círculo de {0} km de radio, ajustado a la densidad de observaciones", it:"Cerchio di {0} km di raggio, adattato alla densità di osservazioni", de:"Kreis mit {0} km Radius, an die Beobachtungsdichte angepasst", pt:"Círculo de {0} km de raio, ajustado à densidade de observações"},
  doRayonFixe:{fr:"Cercle de {0} km de rayon", en:"{0} km radius circle", es:"Círculo de {0} km de radio", it:"Cerchio di {0} km di raggio", de:"Kreis mit {0} km Radius", pt:"Círculo de {0} km de raio"},
  doDensite:{fr:"Estimation de la densité d'observations autour du point…", en:"Estimating observation density around the point…", es:"Estimando la densidad de observaciones alrededor del punto…", it:"Stima della densità di osservazioni attorno al punto…", de:"Beobachtungsdichte um den Punkt wird geschätzt…", pt:"A estimar a densidade de observações em torno do ponto…"},
  crOu_ici:{fr:"ici", en:"here", es:"aquí", it:"qui", de:"hier", pt:"aqui"},
  crOu_ailleurs:{fr:"ailleurs", en:"elsewhere", es:"en otro lugar", it:"altrove", de:"anderswo", pt:"noutro sítio"},
  crVoir:{fr:"Voir l'observation", en:"See the record", es:"Ver la observación", it:"Vedi l'osservazione", de:"Beobachtung ansehen", pt:"Ver a observação"},

  geoHors:{fr:"Hors présence attendue", en:"Outside expected range", es:"Fuera de la presencia esperada", it:"Fuori dalla presenza attesa", de:"Außerhalb des erwarteten Vorkommens", pt:"Fora da presença esperada"},
  geoHorsTitre:{
    fr:"Le modèle géographique d'iNaturalist n'attend pas cette espèce dans la zone. Elle y a pourtant été observée : erreur de détermination, espèce rare ou en expansion, ou limite du modèle.",
    en:"iNaturalist's geographic model does not expect this species in the area. It has been recorded there nonetheless: misidentification, rare or spreading species, or a limit of the model.",
    es:"El modelo geográfico de iNaturalist no espera esta especie en la zona. Sin embargo, se ha observado allí: error de identificación, especie rara o en expansión, o límite del modelo.",
    it:"Il modello geografico di iNaturalist non si aspetta questa specie nella zona. Eppure vi è stata osservata: errore di identificazione, specie rara o in espansione, o limite del modello.",
    de:"Das geografische Modell von iNaturalist erwartet diese Art nicht im Gebiet. Sie wurde dort dennoch beobachtet: Fehlbestimmung, seltene oder sich ausbreitende Art oder eine Grenze des Modells.",
    pt:"O modelo geográfico do iNaturalist não espera esta espécie na zona. No entanto, foi lá observada: erro de identificação, espécie rara ou em expansão, ou limite do modelo."},

  geoPtNon:{fr:"Non attendue à ce point", en:"Not expected at this point", es:"No esperada en este punto", it:"Non attesa in questo punto", de:"An diesem Punkt nicht erwartet", pt:"Não esperada neste ponto"},
  geoPtNonTitre:{
    fr:"Le modèle géographique d'iNaturalist n'attend pas cette espèce à l'endroit de l'observation. Ce n'est pas une impossibilité — espèce rare, en expansion, ou limite du modèle — mais c'est un argument fort contre elle.",
    en:"iNaturalist's geographic model does not expect this species where the observation was made. Not an impossibility — rare or spreading species, or a limit of the model — but a strong argument against it.",
    es:"El modelo geográfico de iNaturalist no espera esta especie en el lugar de la observación. No es imposible (especie rara, en expansión o límite del modelo), pero es un argumento fuerte en su contra.",
    it:"Il modello geografico di iNaturalist non si aspetta questa specie nel luogo dell'osservazione. Non è un'impossibilità — specie rara, in espansione, o limite del modello — ma è un forte argomento contro.",
    de:"Das geografische Modell von iNaturalist erwartet diese Art nicht am Ort der Beobachtung. Das ist keine Unmöglichkeit — seltene oder sich ausbreitende Art oder eine Grenze des Modells —, aber ein starkes Argument gegen sie.",
    pt:"O modelo geográfico do iNaturalist não espera esta espécie no local da observação. Não é uma impossibilidade — espécie rara, em expansão, ou limite do modelo — mas é um argumento forte contra ela."},
  geoPtOui:{fr:"Attendue à ce point", en:"Expected at this point", es:"Esperada en este punto", it:"Attesa in questo punto", de:"An diesem Punkt erwartet", pt:"Esperada neste ponto"},
  geoPtOuiTitre:{
    fr:"Le modèle géographique d'iNaturalist attend cette espèce à l'endroit de l'observation.",
    en:"iNaturalist's geographic model expects this species where the observation was made.",
    es:"El modelo geográfico de iNaturalist espera esta especie en el lugar de la observación.",
    it:"Il modello geografico di iNaturalist si aspetta questa specie nel luogo dell'osservazione.",
    de:"Das geografische Modell von iNaturalist erwartet diese Art am Ort der Beobachtung.",
    pt:"O modelo geográfico do iNaturalist espera esta espécie no local da observação."},
  geoMuet:{fr:"Modèle muet", en:"No model", es:"Modelo mudo", it:"Modello muto", de:"Kein Modell", pt:"Modelo mudo"},
  geoMuetTitre:{
    fr:"Le modèle géographique d'iNaturalist ne couvre pas cette espèce (trop peu d'observations), ou n'a pas pu être lu : aucun verdict.",
    en:"iNaturalist's geographic model does not cover this species (too few records), or could not be read: no verdict.",
    es:"El modelo geográfico de iNaturalist no cubre esta especie (muy pocas observaciones) o no se ha podido leer: sin veredicto.",
    it:"Il modello geografico di iNaturalist non copre questa specie (troppo poche osservazioni), o non è stato possibile leggerlo: nessun verdetto.",
    de:"Das geografische Modell von iNaturalist deckt diese Art nicht ab (zu wenige Beobachtungen) oder konnte nicht gelesen werden: kein Urteil.",
    pt:"O modelo geográfico do iNaturalist não cobre esta espécie (poucas observações) ou não pôde ser lido: sem veredito."},
  geoFiltreToutes:{fr:"Toutes les espèces de la zone", en:"All species in the area", es:"Todas las especies de la zona", it:"Tutte le specie della zona", de:"Alle Arten des Gebiets", pt:"Todas as espécies da zona"},
  geoFiltreAttendues:{fr:"Seulement celles attendues au point", en:"Only those expected at the point", es:"Solo las esperadas en el punto", it:"Solo quelle attese nel punto", de:"Nur die am Punkt erwarteten", pt:"Só as esperadas no ponto"},
  cfJamaisZone:{fr:"jamais observée dans la zone", en:"never recorded in the area", es:"nunca observada en la zona", it:"mai osservata nella zona", de:"nie im Gebiet beobachtet", pt:"nunca observada na zona"},
  cfGroupePoint:{fr:"Compatibles avec le point de l'observation", en:"Compatible with the observation's location", es:"Compatibles con el punto de la observación", it:"Compatibili con il punto dell'osservazione", de:"Passend zum Ort der Beobachtung", pt:"Compatíveis com o ponto da observação"},
  cfGroupePointD:{
    fr:"Espèces que le modèle géographique d'iNaturalist attend à cet endroit (ou qu'il ne couvre pas). Ce sont les confusions à examiner, qu'elles aient été observées dans la zone ou non.",
    en:"Species that iNaturalist's geographic model expects at this location (or does not cover). These are the look-alikes to examine, whether recorded in the area or not.",
    es:"Especies que el modelo geográfico de iNaturalist espera en este lugar (o que no cubre). Son las confusiones que hay que examinar, se hayan observado en la zona o no.",
    it:"Specie che il modello geografico di iNaturalist si aspetta in questo luogo (o che non copre). Sono le confusioni da esaminare, che siano state osservate nella zona o no.",
    de:"Arten, die das geografische Modell von iNaturalist an diesem Ort erwartet (oder nicht abdeckt). Diese Verwechslungen solltest du prüfen, egal ob sie im Gebiet beobachtet wurden oder nicht.",
    pt:"Espécies que o modelo geográfico do iNaturalist espera neste local (ou que não cobre). São as confusões a examinar, tenham ou não sido observadas na zona."},
  cfAucunePoint:{
    fr:"Aucune des confusions connues n'est attendue à cet endroit.",
    en:"None of the known look-alikes is expected at this location.",
    es:"Ninguna de las confusiones conocidas se espera en este lugar.",
    it:"Nessuna delle confusioni note è attesa in questo luogo.",
    de:"Keine der bekannten Verwechslungen wird an diesem Ort erwartet.",
    pt:"Nenhuma das confusões conhecidas é esperada neste local."},
  cfGroupeHorsPoint:{fr:"Non attendues à ce point", en:"Not expected at this point", es:"No esperadas en este punto", it:"Non attese in questo punto", de:"An diesem Punkt nicht erwartet", pt:"Não esperadas neste ponto"},
  cfGroupeHorsPointD:{
    fr:"Le modèle ne les attend pas à cet endroit : elles se confondent ailleurs, mais ici on peut en principe les écarter.",
    en:"The model does not expect them at this location: they get confused elsewhere, but here they can in principle be ruled out.",
    es:"El modelo no las espera en este lugar: se confunden en otros sitios, pero aquí en principio se pueden descartar.",
    it:"Il modello non le attende in questo luogo: vengono confuse altrove, ma qui in linea di principio si possono escludere.",
    de:"Das Modell erwartet sie an diesem Ort nicht: Anderswo werden sie verwechselt, hier lassen sie sich im Prinzip ausschließen.",
    pt:"O modelo não as espera neste local: confundem-se noutros sítios, mas aqui podem, em princípio, ser afastadas."},
  biGeoPoint:{fr:"Non attendue à ce point par iNaturalist", en:"Not expected at this point by iNaturalist", es:"No esperada en este punto según iNaturalist", it:"Non attesa in questo punto secondo iNaturalist", de:"Laut iNaturalist an diesem Punkt nicht erwartet", pt:"Não esperada neste ponto pelo iNaturalist"},
  rpAuPoint:{fr:"Au point de l'observation", en:"At the observation's location", es:"En el punto de la observación", it:"Nel punto dell'osservazione", de:"Am Ort der Beobachtung", pt:"No ponto da observação"},

  cfSourceT_genus:{fr:"Source : repli sur le même genre.", en:"Source: fallback to the same genus.", es:"Fuente: recurso al mismo género.", it:"Fonte: ripiego sullo stesso genere.", de:"Quelle: Rückgriff auf dieselbe Gattung.", pt:"Fonte: recurso ao mesmo género."},
  cfSourceD_genus:{
    fr:"iNaturalist n'a pas fourni de recensement des corrections pour cette espèce. L'outil montre à la place les espèces du même genre observées dans la zone, par fréquence. La parenté n'est pas la ressemblance : c'est une piste, pas une liste de pièges avérés.",
    en:"iNaturalist provided no correction data for this species. The tool shows instead the species of the same genus recorded in the area, by frequency. Kinship is not resemblance: a lead, not a list of proven pitfalls.",
    es:"iNaturalist no ha proporcionado un recuento de correcciones para esta especie. En su lugar, la herramienta muestra las especies del mismo género observadas en la zona, por frecuencia. Parentesco no es parecido: es una pista, no una lista de trampas comprobadas.",
    it:"iNaturalist non ha fornito un conteggio delle correzioni per questa specie. Lo strumento mostra invece le specie dello stesso genere osservate nella zona, per frequenza. Parentela non è somiglianza: è una pista, non un elenco di trappole accertate.",
    de:"iNaturalist liefert für diese Art keine Korrekturdaten. Stattdessen zeigt das Werkzeug die im Gebiet beobachteten Arten derselben Gattung, nach Häufigkeit. Verwandtschaft ist nicht Ähnlichkeit: ein Hinweis, keine Liste belegter Fallstricke.",
    pt:"O iNaturalist não forneceu registo das correções para esta espécie. Em vez disso, a ferramenta mostra as espécies do mesmo género observadas na zona, por frequência. Parentesco não é semelhança: é uma pista, não uma lista de armadilhas comprovadas."},
  cfSourceT_family:{fr:"Source : repli sur la même famille.", en:"Source: fallback to the same family.", es:"Fuente: recurso a la misma familia.", it:"Fonte: ripiego sulla stessa famiglia.", de:"Quelle: Rückgriff auf dieselbe Familie.", pt:"Fonte: recurso à mesma família."},
  cfSourceD_family:{
    fr:"Pas de recensement des corrections, et aucune autre espèce du même genre dans la zone : l'outil montre les espèces de la même famille observées ici. La parenté n'est pas la ressemblance.",
    en:"No correction data, and no other species of the same genus in the area: the tool shows species of the same family recorded here. Kinship is not resemblance.",
    es:"Sin recuento de correcciones y sin otras especies del mismo género en la zona: la herramienta muestra las especies de la misma familia observadas aquí. Parentesco no es parecido.",
    it:"Nessun conteggio delle correzioni, e nessun'altra specie dello stesso genere nella zona: lo strumento mostra le specie della stessa famiglia osservate qui. Parentela non è somiglianza.",
    de:"Keine Korrekturdaten und keine andere Art derselben Gattung im Gebiet: Das Werkzeug zeigt die hier beobachteten Arten derselben Familie. Verwandtschaft ist nicht Ähnlichkeit.",
    pt:"Sem registo das correções e sem outra espécie do mesmo género na zona: a ferramenta mostra as espécies da mesma família observadas aqui. Parentesco não é semelhança."},
  cfSourceT_rien:{fr:"Aucune source.", en:"No source.", es:"Ninguna fuente.", it:"Nessuna fonte.", de:"Keine Quelle.", pt:"Nenhuma fonte."},
  cfSourceD_rien:{
    fr:"Ni recensement des corrections, ni espèce apparentée dans la zone.",
    en:"Neither correction data nor related species in the area.",
    es:"Ni recuento de correcciones ni especies emparentadas en la zona.",
    it:"Né conteggio delle correzioni, né specie affini nella zona.",
    de:"Weder Korrekturdaten noch verwandte Arten im Gebiet.",
    pt:"Nem registo das correções, nem espécie aparentada na zona."},

  crCite:{fr:"cite {0}", en:"mentions {0}", es:"cita {0}", it:"cita {0}", de:"nennt {0}", pt:"cita {0}"},
  crDistingue:{fr:"Ce qui la distingue de {0}", en:"What sets it apart from {0}", es:"Lo que la distingue de {0}", it:"Cosa la distingue da {0}", de:"Was sie von {0} unterscheidet", pt:"O que a distingue de {0}"},
  crDistingueD:{
    fr:"Notes sur cette espèce qui citent une autre espèce retenue. Ce sont presque toujours les critères qui les séparent. Les noms cités sont surlignés.",
    en:"Notes on this species that mention another selected species. These are almost always the criteria that separate them. Mentioned names are highlighted.",
    es:"Notas sobre esta especie que citan otra especie seleccionada. Casi siempre son los criterios que las separan. Los nombres citados aparecen resaltados.",
    it:"Note su questa specie che citano un'altra specie selezionata. Sono quasi sempre i criteri che le separano. I nomi citati sono evidenziati.",
    de:"Notizen zu dieser Art, die eine andere ausgewählte Art nennen. Fast immer sind das die trennenden Merkmale. Genannte Namen sind hervorgehoben.",
    pt:"Notas sobre esta espécie que citam outra espécie retida. Quase sempre são os critérios que as separam. Os nomes citados estão realçados."},
  crDistingueRien:{
    fr:"Aucune note sur cette espèce ne cite les autres espèces retenues. Regarde aussi les critères de l'autre espèce : la comparaison y est peut-être écrite dans l'autre sens.",
    en:"No note on this species mentions the other selected species. Check the other species' criteria too: the comparison may be written the other way round.",
    es:"Ninguna nota sobre esta especie cita las otras especies seleccionadas. Mira también los criterios de la otra especie: quizá la comparación esté escrita en sentido contrario.",
    it:"Nessuna nota su questa specie cita le altre specie selezionate. Guarda anche i criteri dell'altra specie: forse il confronto è scritto nell'altro senso.",
    de:"Keine Notiz zu dieser Art nennt die anderen ausgewählten Arten. Sieh dir auch die Merkmale der anderen Art an: Vielleicht ist der Vergleich dort andersherum notiert.",
    pt:"Nenhuma nota sobre esta espécie cita as outras espécies retidas. Vê também os critérios da outra espécie: a comparação talvez esteja escrita no sentido inverso."},
  crUneSeule:{
    fr:"Retiens au moins deux espèces pour voir les notes qui les départagent.",
    en:"Select at least two species to see the notes that tell them apart.",
    es:"Selecciona al menos dos especies para ver las notas que las diferencian.",
    it:"Seleziona almeno due specie per vedere le note che le distinguono.",
    de:"Wähle mindestens zwei Arten aus, um die Notizen zu sehen, die sie unterscheiden.",
    pt:"Retém pelo menos duas espécies para ver as notas que as distinguem."},
  crAutres:{fr:"Autres critères", en:"Other criteria", es:"Otros criterios", it:"Altri criteri", de:"Weitere Merkmale", pt:"Outros critérios"},
  crAutresD:{
    fr:"Les notes dans ta langue d'abord, puis les plus développées.",
    en:"Notes in your language first, then the most detailed.",
    es:"Primero las notas en tu idioma, después las más detalladas.",
    it:"Prima le note nella tua lingua, poi le più dettagliate.",
    de:"Zuerst Notizen in deiner Sprache, dann die ausführlichsten.",
    pt:"Primeiro as notas na tua língua, depois as mais desenvolvidas."},

  doTitre:{fr:"Partir d'une observation", en:"Start from an observation", es:"Partir de una observación", it:"Partire da un'osservazione", de:"Von einer Beobachtung ausgehen", pt:"Partir de uma observação"},
  doIntro:{
    fr:"Facultatif. Colle le lien d'une observation iNaturalist, ou choisis un point et une date : le lieu devient un cercle autour du point (rayon ajusté à la densité d'observations, ou choisi), la période se centre sur la date, et le groupe devient l'ordre du taxon proposé (ou, au choix, son règne, son embranchement, sa classe, sa famille ou son genre). Tu pourras ensuite redescendre la taxonomie branche par branche.",
    en:"Optional. Paste the link to an iNaturalist observation, or pick a point and a date: the place becomes a circle around the point (radius adjusted to observation density, or chosen), the period centres on the date, and the group becomes the order of the suggested taxon (or, as you choose, its kingdom, phylum, class, family or genus). You can then walk down the taxonomy branch by branch.",
    es:"Opcional. Pega el enlace de una observación de iNaturalist, o elige un punto y una fecha: el lugar pasa a ser un círculo alrededor del punto (radio ajustado a la densidad de observaciones, o elegido), el periodo se centra en la fecha y el grupo pasa a ser el orden del taxón propuesto (o, si prefieres, su reino, filo, clase, familia o género). Después podrás bajar por la taxonomía rama a rama.",
    it:"Facoltativo. Incolla il link di un'osservazione iNaturalist, oppure scegli un punto e una data: il luogo diventa un cerchio attorno al punto (raggio adattato alla densità di osservazioni, o scelto), il periodo si centra sulla data, e il gruppo diventa l'ordine del taxon proposto (o, a scelta, il suo regno, phylum, classe, famiglia o genere). Potrai poi scendere nella tassonomia ramo per ramo.",
    de:"Optional. Füge den Link einer iNaturalist-Beobachtung ein oder wähle einen Punkt und ein Datum: Der Ort wird zu einem Kreis um den Punkt (Radius an die Beobachtungsdichte angepasst oder frei gewählt), der Zeitraum zentriert sich auf das Datum, und die Gruppe wird zur Ordnung des vorgeschlagenen Taxons (oder wahlweise zu seinem Reich, Stamm, seiner Klasse, Familie oder Gattung). Danach kannst du die Taxonomie Ast für Ast hinabsteigen.",
    pt:"Opcional. Cola a ligação de uma observação do iNaturalist, ou escolhe um ponto e uma data: o lugar torna-se um círculo em torno do ponto (raio ajustado à densidade de observações, ou escolhido), o período centra-se na data, e o grupo passa a ser a ordem do táxon proposto (ou, à escolha, o seu reino, filo, classe, família ou género). Depois podes descer na taxonomia ramo a ramo."},
  doPhLien:{fr:"Lien ou numéro d'observation iNaturalist…", en:"iNaturalist observation link or number…", es:"Enlace o número de observación de iNaturalist…", it:"Link o numero di osservazione iNaturalist…", de:"Link oder Nummer der iNaturalist-Beobachtung…", pt:"Ligação ou número de observação do iNaturalist…"},
  doNiveau:{fr:"Groupe à charger", en:"Group to load", es:"Grupo que cargar", it:"Gruppo da caricare", de:"Zu ladende Gruppe", pt:"Grupo a carregar"},
  doN_kingdom:{fr:"Partir du règne", en:"Start from the kingdom", es:"Partir del reino", it:"Parti dal regno", de:"Vom Reich ausgehen", pt:"Partir do reino"},
  doN_phylum:{fr:"Partir de l'embranchement", en:"Start from the phylum", es:"Partir del filo", it:"Parti dal phylum", de:"Vom Stamm ausgehen", pt:"Partir do filo"},
  doN_class:{fr:"Partir de la classe", en:"Start from the class", es:"Partir de la clase", it:"Parti dalla classe", de:"Von der Klasse ausgehen", pt:"Partir da classe"},
  doN_order:{fr:"Partir de l'ordre", en:"Start from the order", es:"Partir del orden", it:"Parti dall'ordine", de:"Von der Ordnung ausgehen", pt:"Partir da ordem"},
  doN_family:{fr:"Partir de la famille", en:"Start from the family", es:"Partir de la familia", it:"Parti dalla famiglia", de:"Von der Familie ausgehen", pt:"Partir da família"},
  doN_genus:{fr:"Partir du genre", en:"Start from the genus", es:"Partir del género", it:"Parti dal genere", de:"Von der Gattung ausgehen", pt:"Partir do género"},
  oTaxonomie:{fr:"Taxonomie", en:"Taxonomy", es:"Taxonomía", it:"Tassonomia", de:"Taxonomie", pt:"Taxonomia"},
  videTaxonomie:{
    fr:"Descendre la taxonomie niveau par niveau, jusqu'aux espèces : la part des observations de chaque groupe ici à cette période, et les photos de ses espèces principales.",
    en:"Walk down the taxonomy level by level, down to species: each group's share of the records here at this time, and photos of its main species.",
    es:"Bajar por la taxonomía nivel a nivel, hasta las especies: la proporción de observaciones de cada grupo aquí en este periodo y las fotos de sus especies principales.",
    it:"Scendi nella tassonomia livello per livello, fino alle specie: la quota di osservazioni di ogni gruppo qui in questo periodo, e le foto delle sue specie principali.",
    de:"Die Taxonomie Stufe für Stufe bis zu den Arten hinabsteigen: der Anteil jeder Gruppe an den Beobachtungen hier in diesem Zeitraum und Fotos ihrer wichtigsten Arten.",
    pt:"Descer na taxonomia nível a nível, até às espécies: a parte das observações de cada grupo aqui neste período, e as fotos das suas espécies principais."},
  taToutes:{fr:"Afficher toutes les espèces ({0})", en:"Show all species ({0})", es:"Mostrar todas las especies ({0})", it:"Mostra tutte le specie ({0})", de:"Alle Arten anzeigen ({0})", pt:"Mostrar todas as espécies ({0})"},
  taGroupes:{fr:"Revenir aux groupes", en:"Back to groups", es:"Volver a los grupos", it:"Torna ai gruppi", de:"Zurück zu den Gruppen", pt:"Voltar aos grupos"},
  taToutesTitre:{fr:"Toutes les espèces de {0} · {1}", en:"All species of {0} · {1}", es:"Todas las especies de {0} · {1}", it:"Tutte le specie di {0} · {1}", de:"Alle Arten von {0} · {1}", pt:"Todas as espécies de {0} · {1}"},
  taRayonKm:{fr:"rayon {0} km", en:"{0} km radius", es:"radio {0} km", it:"raggio {0} km", de:"Radius {0} km", pt:"raio {0} km"},
  taPhotos:{fr:"Photos affichées", en:"Photos shown", es:"Fotos mostradas", it:"Foto mostrate", de:"Angezeigte Fotos", pt:"Fotos mostradas"},
  taVoirCandidats:{fr:"Voir ces espèces dans Candidats", en:"Show these species in Candidates", es:"Ver estas especies en Candidatos", it:"Vedi queste specie in Candidati", de:"Diese Arten in Kandidaten ansehen", pt:"Ver estas espécies em Candidatos"},
  taEspecesDirectes:{fr:"Espèces rattachées directement à {0}", en:"Species placed directly under {0}", es:"Especies asignadas directamente a {0}", it:"Specie collegate direttamente a {0}", de:"Direkt unter {0} eingeordnete Arten", pt:"Espécies ligadas diretamente a {0}"},
  r_subphylum:{fr:"sous-embr.", en:"subphylum", es:"subfilo", it:"subphylum", de:"Unterstamm", pt:"subfilo"},
  r_subclass:{fr:"sous-classe", en:"subclass", es:"subclase", it:"sottoclasse", de:"Unterklasse", pt:"subclasse"},
  r_infraclass:{fr:"infra-classe", en:"infraclass", es:"infraclase", it:"infraclasse", de:"Teilklasse", pt:"infraclasse"},
  r_superorder:{fr:"super-ordre", en:"superorder", es:"superorden", it:"superordine", de:"Überordnung", pt:"superordem"},
  r_infraorder:{fr:"infra-ordre", en:"infraorder", es:"infraorden", it:"infraordine", de:"Teilordnung", pt:"infraordem"},
  r_parvorder:{fr:"parvordre", en:"parvorder", es:"parvorden", it:"parvordine", de:"Kleinordnung", pt:"parvordem"},
  r_zoosection:{fr:"section", en:"zoosection", es:"sección", it:"sezione", de:"Sektion", pt:"secção"},
  r_zoosubsection:{fr:"sous-section", en:"zoosubsection", es:"subsección", it:"sottosezione", de:"Untersektion", pt:"subsecção"},
  r_epifamily:{fr:"épifamille", en:"epifamily", es:"epifamilia", it:"epifamiglia", de:"Epifamilie", pt:"epifamília"},
  r_subfamily:{fr:"sous-famille", en:"subfamily", es:"subfamilia", it:"sottofamiglia", de:"Unterfamilie", pt:"subfamília"},
  r_supertribe:{fr:"super-tribu", en:"supertribe", es:"supertribu", it:"supertribù", de:"Übertribus", pt:"supertribo"},
  r_tribe:{fr:"tribu", en:"tribe", es:"tribu", it:"tribù", de:"Tribus", pt:"tribo"},
  r_subtribe:{fr:"sous-tribu", en:"subtribe", es:"subtribu", it:"sottotribù", de:"Subtribus", pt:"subtribo"},
  r_subgenus:{fr:"sous-genre", en:"subgenus", es:"subgénero", it:"sottogenere", de:"Untergattung", pt:"subgénero"},
  r_section:{fr:"section", en:"section", es:"sección", it:"sezione", de:"Sektion", pt:"secção"},
  r_subsection:{fr:"sous-section", en:"subsection", es:"subsección", it:"sottosezione", de:"Untersektion", pt:"subsecção"},
  r_complex:{fr:"complexe", en:"complex", es:"complejo", it:"complesso", de:"Komplex", pt:"complexo"},
  r_hybrid:{fr:"hybride", en:"hybrid", es:"híbrido", it:"ibrido", de:"Hybride", pt:"híbrido"},
  r_variety:{fr:"variété", en:"variety", es:"variedad", it:"varietà", de:"Varietät", pt:"variedade"},
  r_form:{fr:"forme", en:"form", es:"forma", it:"forma", de:"Form", pt:"forma"},
  guPropose:{fr:"proposé sur l'observation", en:"suggested on the observation", es:"propuesto en la observación", it:"proposto sull'osservazione", de:"auf der Beobachtung vorgeschlagen", pt:"proposto na observação"},
  guDetail:{fr:"{0} obs. · {1} esp.", en:"{0} records · {1} sp.", es:"{0} obs. · {1} esp.", it:"{0} oss. · {1} spp.", de:"{0} Beob. · {1} Arten", pt:"{0} obs. · {1} esp."},
  doLire:{fr:"Lire l'observation", en:"Read the observation", es:"Leer la observación", it:"Leggi l'osservazione", de:"Beobachtung lesen", pt:"Ler a observação"},
  doOuPoint:{fr:"Ou un point et une date", en:"Or a point and a date", es:"O un punto y una fecha", it:"Oppure un punto e una data", de:"Oder ein Punkt und ein Datum", pt:"Ou um ponto e uma data"},
  doPoint:{fr:"Choisir le point sur la carte", en:"Pick the point on the map", es:"Elegir el punto en el mapa", it:"Scegli il punto sulla mappa", de:"Punkt auf der Karte wählen", pt:"Escolher o ponto no mapa"},
  doAppliquer:{fr:"Utiliser", en:"Use", es:"Usar", it:"Usa", de:"Übernehmen", pt:"Usar"},
  doSansPoint:{fr:"aucun point choisi", en:"no point chosen", es:"ningún punto elegido", it:"nessun punto scelto", de:"kein Punkt gewählt", pt:"nenhum ponto escolhido"},
  doLecture:{fr:"Lecture de l'observation…", en:"Reading the observation…", es:"Leyendo la observación…", it:"Lettura dell'osservazione…", de:"Beobachtung wird gelesen…", pt:"A ler a observação…"},
  doLienInvalide:{fr:"Lien ou numéro non reconnu.", en:"Link or number not recognised.", es:"Enlace o número no reconocido.", it:"Link o numero non riconosciuto.", de:"Link oder Nummer nicht erkannt.", pt:"Ligação ou número não reconhecido."},
  doIntrouvable:{fr:"Observation introuvable.", en:"Observation not found.", es:"Observación no encontrada.", it:"Osservazione non trovata.", de:"Beobachtung nicht gefunden.", pt:"Observação não encontrada."},
  doSansLieu:{fr:"Cette observation n'a pas de position lisible.", en:"This observation has no readable position.", es:"Esta observación no tiene una posición legible.", it:"Questa osservazione non ha una posizione leggibile.", de:"Diese Beobachtung hat keine lesbare Position.", pt:"Esta observação não tem uma posição legível."},
  doEchec:{fr:"L'observation n'a pas pu être lue.", en:"The observation could not be read.", es:"No se ha podido leer la observación.", it:"Non è stato possibile leggere l'osservazione.", de:"Die Beobachtung konnte nicht gelesen werden.", pt:"Não foi possível ler a observação."},
  doObs:{fr:"Observation n° {0}", en:"Observation #{0}", es:"Observación n.º {0}", it:"Osservazione n. {0}", de:"Beobachtung Nr. {0}", pt:"Observação n.º {0}"},
  doSansTaxon:{fr:"sans identification", en:"not identified", es:"sin identificación", it:"senza identificazione", de:"ohne Bestimmung", pt:"sem identificação"},
  doFloute:{
    fr:"Position floutée par son auteur (à une vingtaine de kilomètres près) : le rayon ne descend pas sous 50 km.",
    en:"Position obscured by its author (to within about twenty kilometres): the radius does not go below 50 km.",
    es:"Posición difuminada por su autor (con un margen de unos veinte kilómetros): el radio no baja de 50 km.",
    it:"Posizione offuscata dal suo autore (con una precisione di una ventina di chilometri): il raggio non scende sotto i 50 km.",
    de:"Position vom Urheber verschleiert (auf etwa zwanzig Kilometer genau): Der Radius geht nicht unter 50 km.",
    pt:"Posição ocultada pelo autor (com uma margem de uns vinte quilómetros): o raio não desce abaixo de 50 km."},
  doVoirObs:{fr:"Voir sur iNaturalist", en:"See on iNaturalist", es:"Ver en iNaturalist", it:"Vedi su iNaturalist", de:"Auf iNaturalist ansehen", pt:"Ver no iNaturalist"},

  oBilan:{fr:"Bilan", en:"Summary", es:"Balance", it:"Bilancio", de:"Bilanz", pt:"Balanço"},
  videBilan:{
    fr:"Pour chaque espèce retenue, garde-la ou écarte-la avec une raison. Le bilan se recopie dans un commentaire iNaturalist.",
    en:"For each selected species, keep it or rule it out with a reason. The summary can be pasted into an iNaturalist comment.",
    es:"Para cada especie seleccionada, consérvala o descártala con un motivo. El balance se puede copiar en un comentario de iNaturalist.",
    it:"Per ogni specie selezionata, tienila o scartala con un motivo. Il bilancio si copia in un commento iNaturalist.",
    de:"Behalte jede ausgewählte Art oder schließe sie mit einer Begründung aus. Die Bilanz lässt sich in einen iNaturalist-Kommentar kopieren.",
    pt:"Para cada espécie retida, mantém-na ou afasta-a com uma razão. O balanço pode ser copiado para um comentário no iNaturalist."},
  biSansPanier:{fr:"Aucune espèce retenue", en:"No species selected", es:"Ninguna especie seleccionada", it:"Nessuna specie selezionata", de:"Keine Art ausgewählt", pt:"Nenhuma espécie retida"},
  biSansPanierD:{
    fr:"Retiens des candidats depuis l'onglet Candidats, puis reviens ici pour les écarter un à un.",
    en:"Select candidates from the Candidates tab, then come back here to rule them out one by one.",
    es:"Selecciona candidatos en la pestaña Candidatos y vuelve aquí para descartarlos uno a uno.",
    it:"Seleziona dei candidati dalla scheda Candidati, poi torna qui per scartarli uno a uno.",
    de:"Wähle im Reiter Kandidaten Kandidaten aus und komm dann hierher zurück, um sie einzeln auszuschließen.",
    pt:"Retém candidatos no separador Candidatos e volta aqui para os afastar um a um."},
  biIntro:{
    fr:"Garde ou écarte chaque espèce. Les boutons clairs sont ce que les données disent contre elle : un clic l'écarte pour cette raison.",
    en:"Keep or rule out each species. The light buttons are what the data say against it: one click rules it out for that reason.",
    es:"Conserva o descarta cada especie. Los botones claros son lo que los datos dicen en su contra: un clic la descarta por ese motivo.",
    it:"Tieni o scarta ogni specie. I pulsanti chiari sono ciò che i dati dicono contro di essa: un clic la scarta per quel motivo.",
    de:"Behalte oder schließe jede Art aus. Die hellen Schaltflächen zeigen, was die Daten gegen sie sagen: Ein Klick schließt sie aus diesem Grund aus.",
    pt:"Mantém ou afasta cada espécie. Os botões claros são o que os dados dizem contra ela: um clique afasta-a por essa razão."},
  biZone:{fr:"Jamais observée dans la zone", en:"Never recorded in the area", es:"Nunca observada en la zona", it:"Mai osservata nella zona", de:"Nie im Gebiet beobachtet", pt:"Nunca observada na zona"},
  biSaison:{fr:"Aucune observation dans la zone pendant {0}", en:"No record in the area during {0}", es:"Ninguna observación en la zona durante {0}", it:"Nessuna osservazione nella zona durante {0}", de:"Keine Beobachtung im Gebiet während {0}", pt:"Nenhuma observação na zona durante {0}"},
  biPeu:{fr:"Seulement {0} obs. dans la zone pendant {1}", en:"Only {0} records in the area during {1}", es:"Solo {0} obs. en la zona durante {1}", it:"Solo {0} oss. nella zona durante {1}", de:"Nur {0} Beob. im Gebiet während {1}", pt:"Só {0} obs. na zona durante {1}"},
  biGeo:{fr:"Hors de la présence attendue par iNaturalist", en:"Outside the range expected by iNaturalist", es:"Fuera de la presencia esperada por iNaturalist", it:"Fuori dalla presenza attesa da iNaturalist", de:"Außerhalb des von iNaturalist erwarteten Vorkommens", pt:"Fora da presença esperada pelo iNaturalist"},
  biRienContre:{fr:"Rien dans les données ne l'écarte.", en:"Nothing in the data rules it out.", es:"Nada en los datos la descarta.", it:"Nulla nei dati la esclude.", de:"Nichts in den Daten schließt sie aus.", pt:"Nada nos dados a afasta."},
  biAppliquer:{fr:"Écarter pour cette raison", en:"Rule out for this reason", es:"Descartar por este motivo", it:"Scarta per questo motivo", de:"Aus diesem Grund ausschließen", pt:"Afastar por esta razão"},
  biGardee:{fr:"Gardée", en:"Kept", es:"Conservada", it:"Tenuta", de:"Behalten", pt:"Mantida"},
  biEcarter:{fr:"Écartée :", en:"Ruled out:", es:"Descartada:", it:"Scartata:", de:"Ausgeschlossen:", pt:"Afastada:"},
  biR_saison:{fr:"hors saison", en:"out of season", es:"fuera de temporada", it:"fuori stagione", de:"außerhalb der Saison", pt:"fora de época"},
  biR_geo:{fr:"hors présence attendue", en:"outside expected range", es:"fuera de la presencia esperada", it:"fuori dalla presenza attesa", de:"außerhalb des erwarteten Vorkommens", pt:"fora da presença esperada"},
  biR_zone:{fr:"absente de la zone", en:"absent from the area", es:"ausente de la zona", it:"assente dalla zona", de:"nicht im Gebiet", pt:"ausente da zona"},
  biR_critere:{fr:"critère visible", en:"visible feature", es:"criterio visible", it:"criterio visibile", de:"sichtbares Merkmal", pt:"critério visível"},
  biR_autre:{fr:"autre raison", en:"other reason", es:"otro motivo", it:"altro motivo", de:"anderer Grund", pt:"outra razão"},
  biPhNote:{fr:"Précision (ex. : tarses jaunes visibles)", en:"Detail (e.g. yellow tarsi visible)", es:"Detalle (ej.: tarsos amarillos visibles)", it:"Dettaglio (es.: tarsi gialli visibili)", de:"Detail (z. B. gelbe Tarsen sichtbar)", pt:"Pormenor (ex.: tarsos amarelos visíveis)"},
  biResume:{fr:"Bilan à recopier", en:"Summary to paste", es:"Balance para copiar", it:"Bilancio da copiare", de:"Bilanz zum Kopieren", pt:"Balanço a copiar"},
  biCopier:{fr:"Copier", en:"Copy", es:"Copiar", it:"Copia", de:"Kopieren", pt:"Copiar"},
  biCopie:{fr:"Copié.", en:"Copied.", es:"Copiado.", it:"Copiato.", de:"Kopiert.", pt:"Copiado."},
  biEntete:{fr:"Candidats examinés — {0}", en:"Candidates examined — {0}", es:"Candidatos examinados — {0}", it:"Candidati esaminati — {0}", de:"Geprüfte Kandidaten — {0}", pt:"Candidatos examinados — {0}"},
  biGardees:{fr:"Gardée(s) :", en:"Kept:", es:"Conservada(s):", it:"Tenuta/e:", de:"Behalten:", pt:"Mantida(s):"},
  biEcartees:{fr:"Écartée(s) :", en:"Ruled out:", es:"Descartada(s):", it:"Scartata/e:", de:"Ausgeschlossen:", pt:"Afastada(s):"},
  biObs:{fr:"observation n° {0}", en:"observation #{0}", es:"observación n.º {0}", it:"osservazione n. {0}", de:"Beobachtung Nr. {0}", pt:"observação n.º {0}"},
  biAutour:{fr:"autour de {0} (rayon {1} km)", en:"around {0} ({1} km radius)", es:"alrededor de {0} (radio {1} km)", it:"attorno a {0} (raggio {1} km)", de:"um {0} (Radius {1} km)", pt:"em torno de {0} (raio {1} km)"},
  biPied:{
    fr:"(Fréquences et saisons d'après les observations iNaturalist de la zone ; présence attendue d'après le modèle géographique d'iNaturalist.)",
    en:"(Frequencies and seasons from iNaturalist records in the area; expected presence from iNaturalist's geographic model.)",
    es:"(Frecuencias y temporadas según las observaciones de iNaturalist en la zona; presencia esperada según el modelo geográfico de iNaturalist.)",
    it:"(Frequenze e stagioni in base alle osservazioni iNaturalist della zona; presenza attesa in base al modello geografico di iNaturalist.)",
    de:"(Häufigkeiten und Saisons nach den iNaturalist-Beobachtungen im Gebiet; erwartetes Vorkommen nach dem geografischen Modell von iNaturalist.)",
    pt:"(Frequências e épocas segundo as observações do iNaturalist na zona; presença esperada segundo o modelo geográfico do iNaturalist.)"},

  oRepartition:{fr:"Répartition", en:"Range", es:"Distribución", it:"Distribuzione", de:"Verbreitung", pt:"Distribuição"},
  videRepartition:{
    fr:"L'aire de répartition de chaque candidat retenu, d'après iNaturalist, sur la même carte et sous les mêmes couleurs.",
    en:"The range of each selected candidate, according to iNaturalist, on the same map and under the same colours.",
    es:"El área de distribución de cada candidato seleccionado, según iNaturalist, en el mismo mapa y con los mismos colores.",
    it:"L'areale di distribuzione di ogni candidato selezionato, secondo iNaturalist, sulla stessa mappa e con gli stessi colori.",
    de:"Das Verbreitungsgebiet jedes ausgewählten Kandidaten laut iNaturalist, auf derselben Karte und in denselben Farben.",
    pt:"A área de distribuição de cada candidato retido, segundo o iNaturalist, no mesmo mapa e com as mesmas cores."},
  rpC_attendue:{fr:"Présence attendue", en:"Expected range", es:"Presencia esperada", it:"Presenza attesa", de:"Erwartetes Vorkommen", pt:"Presença esperada"},
  rpC_observations:{fr:"Observations", en:"Records", es:"Observaciones", it:"Osservazioni", de:"Beobachtungen", pt:"Observações"},
  rpEspece:{fr:"Espèce", en:"Species", es:"Especie", it:"Specie", de:"Art", pt:"Espécie"},
  rpRecadrer:{fr:"Recadrer sur la zone", en:"Back to the area", es:"Volver a la zona", it:"Inquadra la zona", de:"Auf Gebiet zoomen", pt:"Enquadrar na zona"},
  rpDispoOui:{fr:"✓ affichée", en:"✓ shown", es:"✓ mostrada", it:"✓ mostrata", de:"✓ angezeigt", pt:"✓ mostrada"},
  rpDispoNon:{fr:"— rien près de la zone", en:"— nothing near the area", es:"— nada cerca de la zona", it:"— niente vicino alla zona", de:"— nichts in Gebietsnähe", pt:"— nada perto da zona"},
  rpDispoAbsente:{fr:"— non disponible", en:"— not available", es:"— no disponible", it:"— non disponibile", de:"— nicht verfügbar", pt:"— não disponível"},
  rpDispoInconnu:{fr:"? non vérifiable", en:"? cannot check", es:"? no verificable", it:"? non verificabile", de:"? nicht prüfbar", pt:"? não verificável"},
  rpTrop:{fr:"Seules les {0} premières espèces retenues sont cartographiées.",
    en:"Only the first {0} selected species are mapped.",
    es:"Solo se cartografían las {0} primeras especies seleccionadas.",
    it:"Solo le prime {0} specie selezionate sono cartografate.",
    de:"Nur die ersten {0} ausgewählten Arten werden kartiert.",
    pt:"Só as primeiras {0} espécies retidas são cartografadas."},
  rpNoteAttendue:{
    fr:"Présence attendue : le modèle géographique d'iNaturalist, celui qu'utilise l'identification automatique. Il indique, par mailles d'une quarantaine de kilomètres, où l'espèce est attendue d'après l'ensemble des observations. Disponible pour la plupart des espèces bien observées.",
    en:"Expected range: iNaturalist's geographic model, the one used by automatic identification. It shows, in cells about forty kilometres wide, where the species is expected given all records. Available for most well-recorded species.",
    es:"Presencia esperada: el modelo geográfico de iNaturalist, el que usa la identificación automática. Indica, en celdas de unos cuarenta kilómetros, dónde se espera la especie según el conjunto de observaciones. Disponible para la mayoría de las especies bien observadas.",
    it:"Presenza attesa: il modello geografico di iNaturalist, quello usato dall'identificazione automatica. Indica, in celle di una quarantina di chilometri, dove la specie è attesa in base all'insieme delle osservazioni. Disponibile per la maggior parte delle specie ben osservate.",
    de:"Erwartetes Vorkommen: das geografische Modell von iNaturalist, das auch die automatische Bestimmung nutzt. Es zeigt in Zellen von rund vierzig Kilometern, wo die Art nach allen Beobachtungen erwartet wird. Für die meisten gut beobachteten Arten verfügbar.",
    pt:"Presença esperada: o modelo geográfico do iNaturalist, o mesmo que a identificação automática usa. Indica, em quadrículas de cerca de quarenta quilómetros, onde a espécie é esperada segundo o conjunto das observações. Disponível para a maioria das espécies bem observadas."},
  rpNoteObservations:{
    fr:"Observations : la grille de toutes les observations de l'espèce dans le monde, au niveau de validation choisi. Plus la maille est intense, plus elle compte d'observations.",
    en:"Records: the grid of all records of the species worldwide, at the chosen validation level. The more intense a cell, the more records it holds.",
    es:"Observaciones: la cuadrícula de todas las observaciones de la especie en el mundo, con el nivel de validación elegido. Cuanto más intensa es una celda, más observaciones tiene.",
    it:"Osservazioni: la griglia di tutte le osservazioni della specie nel mondo, al livello di validazione scelto. Più la cella è intensa, più osservazioni contiene.",
    de:"Beobachtungen: das Raster aller Beobachtungen der Art weltweit, auf der gewählten Bestätigungsstufe. Je kräftiger eine Zelle, desto mehr Beobachtungen enthält sie.",
    pt:"Observações: a grelha de todas as observações da espécie no mundo, ao nível de validação escolhido. Quanto mais intensa a quadrícula, mais observações tem."},
  rpSansPanier:{fr:"Aucune espèce retenue", en:"No species selected", es:"Ninguna especie seleccionada", it:"Nessuna specie selezionata", de:"Keine Art ausgewählt", pt:"Nenhuma espécie retida"},
  rpSansPanierD:{
    fr:"Retiens au moins un candidat depuis l'onglet Candidats pour voir sa répartition.",
    en:"Select at least one candidate from the Candidates tab to see its range.",
    es:"Selecciona al menos un candidato en la pestaña Candidatos para ver su distribución.",
    it:"Seleziona almeno un candidato dalla scheda Candidati per vederne la distribuzione.",
    de:"Wähle im Reiter Kandidaten mindestens einen Kandidaten aus, um seine Verbreitung zu sehen.",
    pt:"Retém pelo menos um candidato no separador Candidatos para ver a sua distribuição."},
}).forEach(([k, v]) => { for (const l in v) TEXTES[l][k] = v[l]; });
